// Code generated by github.com/kralicky/codegen/cli. DO NOT EDIT.
// source: github.com/pomerium/pomerium/pkg/grpc/databroker/databroker.proto

package databroker

import (
	context "context"
	errors "errors"
	cli "github.com/kralicky/codegen/cli"
	cliutil "github.com/kralicky/codegen/pkg/cliutil"
	flagutil "github.com/kralicky/codegen/pkg/flagutil"
	cobra "github.com/spf13/cobra"
	pflag "github.com/spf13/pflag"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	strings "strings"
)

type (
	contextKey_DataBrokerService_type      struct{}
	contextInjector_DataBrokerService_type struct{}
)

var (
	contextKey_DataBrokerService     contextKey_DataBrokerService_type
	DataBrokerServiceContextInjector contextInjector_DataBrokerService_type
)

func (contextInjector_DataBrokerService_type) NewClient(cc grpc.ClientConnInterface) DataBrokerServiceClient {
	return NewDataBrokerServiceClient(cc)
}

func (contextInjector_DataBrokerService_type) UnderlyingConn(client DataBrokerServiceClient) grpc.ClientConnInterface {
	return client.(*dataBrokerServiceClient).cc
}

func (contextInjector_DataBrokerService_type) ContextWithClient(ctx context.Context, client DataBrokerServiceClient) context.Context {
	return context.WithValue(ctx, contextKey_DataBrokerService, client)
}

func (contextInjector_DataBrokerService_type) ClientFromContext(ctx context.Context) (DataBrokerServiceClient, bool) {
	client, ok := ctx.Value(contextKey_DataBrokerService).(DataBrokerServiceClient)
	return client, ok
}

type (
	contextKey_CheckpointService_type      struct{}
	contextInjector_CheckpointService_type struct{}
)

var (
	contextKey_CheckpointService     contextKey_CheckpointService_type
	CheckpointServiceContextInjector contextInjector_CheckpointService_type
)

func (contextInjector_CheckpointService_type) NewClient(cc grpc.ClientConnInterface) CheckpointServiceClient {
	return NewCheckpointServiceClient(cc)
}

func (contextInjector_CheckpointService_type) UnderlyingConn(client CheckpointServiceClient) grpc.ClientConnInterface {
	return client.(*checkpointServiceClient).cc
}

func (contextInjector_CheckpointService_type) ContextWithClient(ctx context.Context, client CheckpointServiceClient) context.Context {
	return context.WithValue(ctx, contextKey_CheckpointService, client)
}

func (contextInjector_CheckpointService_type) ClientFromContext(ctx context.Context) (CheckpointServiceClient, bool) {
	client, ok := ctx.Value(contextKey_CheckpointService).(CheckpointServiceClient)
	return client, ok
}

var extraCmds_DataBrokerService []*cobra.Command

func addExtraDataBrokerServiceCmd(custom *cobra.Command) {
	extraCmds_DataBrokerService = append(extraCmds_DataBrokerService, custom)
}

func BuildDataBrokerServiceCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "data-broker-service",
		Short:             `The DataBrokerService stores key-value data.`,
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
	}

	cliutil.AddSubcommands(cmd, append([]*cobra.Command{
		BuildDataBrokerServiceAcquireLeaseCmd(),
		BuildDataBrokerServiceClearCmd(),
		BuildDataBrokerServiceGetCmd(),
		BuildDataBrokerServiceGetOptionsCmd(),
		BuildDataBrokerServiceListTypesCmd(),
		BuildDataBrokerServicePutCmd(),
		BuildDataBrokerServiceQueryCmd(),
		BuildDataBrokerServiceReleaseLeaseCmd(),
		BuildDataBrokerServiceRenewLeaseCmd(),
		BuildDataBrokerServiceServerInfoCmd(),
		BuildDataBrokerServiceSetOptionsCmd(),
		BuildDataBrokerServiceSyncCmd(),
		BuildDataBrokerServiceSyncLatestCmd(),
	}, extraCmds_DataBrokerService...)...)
	cli.AddOutputFlag(cmd)
	return cmd
}

func BuildDataBrokerServiceAcquireLeaseCmd() *cobra.Command {
	in := &AcquireLeaseRequest{}
	cmd := &cobra.Command{
		Use:               "acquire-lease",
		Short:             "AcquireLease acquires a distributed mutex lease.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.AcquireLease(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceClearCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "clear",
		Short:             "Clear removes all records from the databroker.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			response, err := client.Clear(cmd.Context(), &emptypb.Empty{})
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	return cmd
}

func BuildDataBrokerServiceGetCmd() *cobra.Command {
	in := &GetRequest{}
	cmd := &cobra.Command{
		Use:               "get",
		Short:             "Get gets a record.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.Get(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceGetOptionsCmd() *cobra.Command {
	in := &GetOptionsRequest{}
	cmd := &cobra.Command{
		Use:               "get-options",
		Short:             "GetOptions gets the options for a type in the databroker.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.GetOptions(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceListTypesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "list-types",
		Short:             "ListTypes lists all the known record types.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			response, err := client.ListTypes(cmd.Context(), &emptypb.Empty{})
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	return cmd
}

func BuildDataBrokerServicePutCmd() *cobra.Command {
	in := &PutRequest{}
	cmd := &cobra.Command{
		Use:               "put",
		Short:             "Put saves a record.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if cmd.Flags().Lookup("interactive").Value.String() == "true" {
				if edited, err := cliutil.EditInteractive(in); err != nil {
					return err
				} else {
					in = edited
				}
			} else if fileName := cmd.Flags().Lookup("file").Value.String(); fileName != "" {
				if err := cliutil.LoadFromFile(in, fileName); err != nil {
					return err
				}
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.Put(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().StringP("file", "f", "", "path to a file containing the config, or - to read from stdin")
	cmd.Flags().BoolP("interactive", "i", false, "edit the config interactively in an editor")
	cmd.MarkFlagsMutuallyExclusive("file", "interactive")
	cmd.MarkFlagFilename("file")
	return cmd
}

func BuildDataBrokerServiceQueryCmd() *cobra.Command {
	in := &QueryRequest{}
	cmd := &cobra.Command{
		Use:               "query",
		Short:             "Query queries for records.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.Query(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceReleaseLeaseCmd() *cobra.Command {
	in := &ReleaseLeaseRequest{}
	cmd := &cobra.Command{
		Use:               "release-lease",
		Short:             "ReleaseLease releases a distributed mutex lease.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			_, err := client.ReleaseLease(cmd.Context(), in)
			if err != nil {
				return err
			}
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceRenewLeaseCmd() *cobra.Command {
	in := &RenewLeaseRequest{}
	cmd := &cobra.Command{
		Use:               "renew-lease",
		Short:             "RenewLease renews a distributed mutex lease.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			_, err := client.RenewLease(cmd.Context(), in)
			if err != nil {
				return err
			}
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceServerInfoCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "server-info",
		Short:             "ServerInfo returns information about the databroker server.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			response, err := client.ServerInfo(cmd.Context(), &emptypb.Empty{})
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	return cmd
}

func BuildDataBrokerServiceSetOptionsCmd() *cobra.Command {
	in := &SetOptionsRequest{}
	cmd := &cobra.Command{
		Use:               "set-options",
		Short:             "SetOptions sets the options for a type in the databroker.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.SetOptions(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceSyncCmd() *cobra.Command {
	in := &SyncRequest{}
	cmd := &cobra.Command{
		Use:               "sync",
		Short:             "Sync streams changes to records after the specified version.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.Sync(cmd.Context(), in)
			if err != nil {
				return err
			}
			return cli.RenderStreamingOutput(cmd, response)
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func BuildDataBrokerServiceSyncLatestCmd() *cobra.Command {
	in := &SyncLatestRequest{}
	cmd := &cobra.Command{
		Use:               "sync-latest",
		Short:             "SyncLatest streams the latest version of every record.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := DataBrokerServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.SyncLatest(cmd.Context(), in)
			if err != nil {
				return err
			}
			return cli.RenderStreamingOutput(cmd, response)
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

var extraCmds_CheckpointService []*cobra.Command

func addExtraCheckpointServiceCmd(custom *cobra.Command) {
	extraCmds_CheckpointService = append(extraCmds_CheckpointService, custom)
}

func BuildCheckpointServiceCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:               "checkpoint-service",
		Short:             `The CheckpointService gets and sets checkpoints.`,
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
	}

	cliutil.AddSubcommands(cmd, append([]*cobra.Command{
		BuildCheckpointServiceGetCheckpointCmd(),
		BuildCheckpointServiceSetCheckpointCmd(),
	}, extraCmds_CheckpointService...)...)
	cli.AddOutputFlag(cmd)
	return cmd
}

func BuildCheckpointServiceGetCheckpointCmd() *cobra.Command {
	in := &GetCheckpointRequest{}
	cmd := &cobra.Command{
		Use:               "get-checkpoint",
		Short:             "GetCheckpoint gets the checkpoint.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := CheckpointServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.GetCheckpoint(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	return cmd
}

func BuildCheckpointServiceSetCheckpointCmd() *cobra.Command {
	in := &SetCheckpointRequest{}
	cmd := &cobra.Command{
		Use:               "set-checkpoint",
		Short:             "SetCheckpoint sets the checkpoint.",
		Args:              cobra.NoArgs,
		ValidArgsFunction: cobra.NoFileCompletions,
		RunE: func(cmd *cobra.Command, args []string) error {
			client, ok := CheckpointServiceContextInjector.ClientFromContext(cmd.Context())
			if !ok {
				cmd.PrintErrln("failed to get client from context")
				return nil
			}
			if in == nil {
				return errors.New("no input provided")
			}
			response, err := client.SetCheckpoint(cmd.Context(), in)
			if err != nil {
				return err
			}
			cli.RenderOutput(cmd, response)
			return nil
		},
	}
	cmd.Flags().AddFlagSet(in.FlagSet())
	return cmd
}

func (in *AcquireLeaseRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("AcquireLeaseRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Name, strings.Join(append(prefix, "name"), "."), "", "Name is the name of the lease. Only a single client can hold the lease on")
	fs.Var(flagutil.DurationpbValue(nil, &in.Duration), strings.Join(append(prefix, "duration"), "."), "Duration is the duration of the lease. After the duration is reached the")
	return fs
}

func (in *GetRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("GetRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Type, strings.Join(append(prefix, "type"), "."), "", "")
	fs.StringVar(&in.Id, strings.Join(append(prefix, "id"), "."), "", "")
	return fs
}

func (in *GetOptionsRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("GetOptionsRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Type, strings.Join(append(prefix, "type"), "."), "", "")
	return fs
}

func (in *PutRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("PutRequest", pflag.ExitOnError)
	fs.SortFlags = true
	return fs
}

func (in *QueryRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("QueryRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Type, strings.Join(append(prefix, "type"), "."), "", "")
	fs.StringVar(&in.Query, strings.Join(append(prefix, "query"), "."), "", "")
	fs.Int64Var(&in.Offset, strings.Join(append(prefix, "offset"), "."), 0, "")
	fs.Int64Var(&in.Limit, strings.Join(append(prefix, "limit"), "."), 0, "")
	fs.Var(flagutil.UintPtrValue(nil, &in.MinimumRecordVersionHint), strings.Join(append(prefix, "minimum-record-version-hint"), "."), "")
	return fs
}

func (in *ReleaseLeaseRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("ReleaseLeaseRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Name, strings.Join(append(prefix, "name"), "."), "", "")
	fs.StringVar(&in.Id, strings.Join(append(prefix, "id"), "."), "", "")
	return fs
}

func (in *RenewLeaseRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("RenewLeaseRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Name, strings.Join(append(prefix, "name"), "."), "", "")
	fs.StringVar(&in.Id, strings.Join(append(prefix, "id"), "."), "", "")
	fs.Var(flagutil.DurationpbValue(nil, &in.Duration), strings.Join(append(prefix, "duration"), "."), "")
	return fs
}

func (in *SetOptionsRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("SetOptionsRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Type, strings.Join(append(prefix, "type"), "."), "", "")
	if in.Options == nil {
		in.Options = &Options{}
	}
	fs.AddFlagSet(in.Options.FlagSet(append(prefix, "options")...))
	return fs
}

func (in *Options) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("Options", pflag.ExitOnError)
	fs.SortFlags = true
	fs.Var(flagutil.UintPtrValue(nil, &in.Capacity), strings.Join(append(prefix, "capacity"), "."), "capacity sets a maximum size for the given type. Once the capacity is")
	fs.StringSliceVar(&in.IndexableFields, strings.Join(append(prefix, "indexable-fields"), "."), nil, "indexable_fields sets the protobuf fields that should be indexed on")
	fs.Var(flagutil.DurationpbValue(nil, &in.Ttl), strings.Join(append(prefix, "ttl"), "."), "ttl sets the time-to-live for records of this type. Records whose")
	return fs
}

func (in *SyncRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("SyncRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.Uint64Var(&in.ServerVersion, strings.Join(append(prefix, "server-version"), "."), 0, "")
	fs.Uint64Var(&in.RecordVersion, strings.Join(append(prefix, "record-version"), "."), 0, "")
	fs.StringVar(&in.Type, strings.Join(append(prefix, "type"), "."), "", "")
	fs.Var(flagutil.BoolPtrValue(nil, &in.Wait), strings.Join(append(prefix, "wait"), "."), "Wait indicates whether to wait for changes or to close the stream on the")
	return fs
}

func (in *SyncLatestRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("SyncLatestRequest", pflag.ExitOnError)
	fs.SortFlags = true
	fs.StringVar(&in.Type, strings.Join(append(prefix, "type"), "."), "", "")
	return fs
}

func (in *SetCheckpointRequest) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("SetCheckpointRequest", pflag.ExitOnError)
	fs.SortFlags = true
	if in.Checkpoint == nil {
		in.Checkpoint = &Checkpoint{}
	}
	fs.AddFlagSet(in.Checkpoint.FlagSet(append(prefix, "checkpoint")...))
	return fs
}

func (in *Checkpoint) FlagSet(prefix ...string) *pflag.FlagSet {
	fs := pflag.NewFlagSet("Checkpoint", pflag.ExitOnError)
	fs.SortFlags = true
	fs.Uint64Var(&in.ServerVersion, strings.Join(append(prefix, "server-version"), "."), 0, "")
	fs.Uint64Var(&in.RecordVersion, strings.Join(append(prefix, "record-version"), "."), 0, "")
	return fs
}
