// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomerium/pomerium/pkg/ssh (interfaces: PolicyIndexSubscriber)
//
// Generated by this command:
//
//	mockgen -typed -destination ./mock/mock_policy_index.go . PolicyIndexSubscriber
//

// Package mock_ssh is a generated GoMock package.
package mock_ssh

import (
	reflect "reflect"

	common "github.com/pomerium/pomerium/pkg/ssh/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyIndexSubscriber is a mock of PolicyIndexSubscriber interface.
type MockPolicyIndexSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyIndexSubscriberMockRecorder
	isgomock struct{}
}

// MockPolicyIndexSubscriberMockRecorder is the mock recorder for MockPolicyIndexSubscriber.
type MockPolicyIndexSubscriberMockRecorder struct {
	mock *MockPolicyIndexSubscriber
}

// NewMockPolicyIndexSubscriber creates a new mock instance.
func NewMockPolicyIndexSubscriber(ctrl *gomock.Controller) *MockPolicyIndexSubscriber {
	mock := &MockPolicyIndexSubscriber{ctrl: ctrl}
	mock.recorder = &MockPolicyIndexSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyIndexSubscriber) EXPECT() *MockPolicyIndexSubscriberMockRecorder {
	return m.recorder
}

// UpdateEnabledStaticPorts mocks base method.
func (m *MockPolicyIndexSubscriber) UpdateEnabledStaticPorts(allowedStaticPorts []uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateEnabledStaticPorts", allowedStaticPorts)
}

// UpdateEnabledStaticPorts indicates an expected call of UpdateEnabledStaticPorts.
func (mr *MockPolicyIndexSubscriberMockRecorder) UpdateEnabledStaticPorts(allowedStaticPorts any) *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnabledStaticPorts", reflect.TypeOf((*MockPolicyIndexSubscriber)(nil).UpdateEnabledStaticPorts), allowedStaticPorts)
	return &MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall{Call: call}
}

// MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall wrap *gomock.Call
type MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall) Return() *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall) Do(f func([]uint)) *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall) DoAndReturn(f func([]uint)) *MockPolicyIndexSubscriberUpdateEnabledStaticPortsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTunnelAuthorizedRoutes mocks base method.
func (m *MockPolicyIndexSubscriber) UpdateTunnelAuthorizedRoutes(routes []common.RouteInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateTunnelAuthorizedRoutes", routes)
}

// UpdateTunnelAuthorizedRoutes indicates an expected call of UpdateTunnelAuthorizedRoutes.
func (mr *MockPolicyIndexSubscriberMockRecorder) UpdateTunnelAuthorizedRoutes(routes any) *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTunnelAuthorizedRoutes", reflect.TypeOf((*MockPolicyIndexSubscriber)(nil).UpdateTunnelAuthorizedRoutes), routes)
	return &MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall{Call: call}
}

// MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall wrap *gomock.Call
type MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall) Return() *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall) Do(f func([]common.RouteInfo)) *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall) DoAndReturn(f func([]common.RouteInfo)) *MockPolicyIndexSubscriberUpdateTunnelAuthorizedRoutesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
