FROM busybox:latest@sha256:db142d433cdde11f10ae479dbf92f3b13d693fd1c91053da9979728cceb1dc68 AS build
RUN touch /config.yaml

FROM gcr.io/distroless/base-debian12:debug-nonroot@sha256:d88b20e321d3f81d9f712bff98caffef5d4cd2066bbda3e18c1c81d3441d4d4c
ENV AUTOCERT_DIR=/data/autocert
WORKDIR /pomerium
COPY pomerium /bin/
COPY --from=build /config.yaml /pomerium/config.yaml
ENTRYPOINT [ "/bin/pomerium" ]
CMD ["-config","/pomerium/config.yaml"]
