FROM busybox:latest@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e AS build
RUN touch /config.yaml

FROM debian:bookworm-slim@sha256:4724b8cc51e33e398f0e2e15e18d5ec2851ff0c2280647e1310bc1642182655d
ARG DEBIAN_FRONTEND=noninteractive
ENV AUTOCERT_DIR=/data/autocert
WORKDIR /pomerium
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        curl \
        dnsutils \
        iproute2 \
        iputils-ping \
        jq \
        lsof \
        netcat-openbsd \
        openssl \
        procps \
        strace \
        traceroute \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /data/autocert /pomerium \
    && chown -R 65532:65532 /data /pomerium
COPY pomerium /bin/
COPY --chown=65532:65532 --from=build /config.yaml /pomerium/config.yaml
USER 65532:65532
ENTRYPOINT [ "/bin/pomerium" ]
CMD ["--config","/pomerium/config.yaml"]
