project_name: pomerium

release:
  github:
    owner: pomerium
    name: pomerium
  name_template: "v{{.Version}}"

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - make build-deps

builds:
  - id: pomerium
    main: cmd/pomerium/main.go
    binary: pomerium
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: arm64

    ldflags:
      - -s -w
      - -X github.com/pomerium/pomerium/internal/version.Version={{.Version}}
      - -X github.com/pomerium/pomerium/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/pomerium/pomerium/internal/version.BuildMeta={{.Timestamp}}
      - -X github.com/pomerium/pomerium/internal/version.ProjectName=pomerium
      - -X github.com/pomerium/pomerium/internal/version.ProjectURL=https://wwww.pomerium.io

    hooks:
      post:
        - cmd: ./scripts/embed-envoy.bash {{ .Path }}
          env: # e.g. darwin_amd64
            - TARGET={{ .Target }}

  - id: pomerium-cli
    main: cmd/pomerium-cli/main.go
    binary: pomerium-cli
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

    ldflags:
      - -s -w
      - -X github.com/pomerium/pomerium/internal/version.Version={{.Version}}
      - -X github.com/pomerium/pomerium/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/pomerium/pomerium/internal/version.BuildMeta={{.Timestamp}}
      - -X github.com/pomerium/pomerium/internal/version.ProjectName=pomerium
      - -X github.com/pomerium/pomerium/internal/version.ProjectURL=https://wwww.pomerium.io

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - pomerium
      - pomerium-cli
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}+next"

dockers:
  - image_templates:
      - "pomerium/pomerium:{{ .Tag }}"
    dockerfile: .github/Dockerfile-release
    binaries:
      - pomerium
      - pomerium-cli
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"

  - image_templates:
      - "gcr.io/pomerium-io/pomerium:{{ .Tag }}-cloudrun"
    dockerfile: .github/Dockerfile-cloudrun
    binaries:
      - pomerium
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"

  - goarch: arm64
    image_templates:
      - "pomerium/pomerium:arm64v8-{{ .Tag }}"
    dockerfile: .github/Dockerfile-release.arm64v8
    binaries:
      - pomerium
      - pomerium-cli
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"
