version: 2

project_name: pomerium

release:
  prerelease: auto
  github:
    owner: pomerium
    name: pomerium
  name_template: "v{{.Version}}"

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - make get-envoy
    - make build-deps
    - make build-ui

builds:
  - id: pomerium
    main: cmd/pomerium/main.go
    binary: pomerium
    goarch:
      - arm64
    goos:
      - darwin

    ldflags:
      - -s -w
      - -X github.com/pomerium/pomerium/internal/version.Version={{.Version}}
      - -X github.com/pomerium/pomerium/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/pomerium/pomerium/internal/version.Timestamp={{.Timestamp}}
      - -X github.com/pomerium/pomerium/internal/version.ProjectName=pomerium
      - -X github.com/pomerium/pomerium/internal/version.ProjectURL=https://www.pomerium.io

notarize:
  macos_native:
    - enabled: '{{ isEnvSet "SIGN_BINARIES" }}'
      sign:
        identity: CC3DF18605EE508E04ABA66690466E1721314BF5
      notarize:
        profile_name: pomerium_proxy
        wait: true

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    id: pomerium
    ids:
      - pomerium
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: "{{ .Version }}+next+{{ .ShortCommit }}"
