project_name: pomerium

release:
  github:
    owner: pomerium
    name: pomerium
  name_template: "v{{.Version}}"

before:
  hooks:
    - go mod download

builds:
  - id: pomerium
    main: cmd/pomerium/main.go
    binary: pomerium
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

    ldflags:
      - -s -w
      - -X github.com/pomerium/pomerium/internal/version.Version={{.Version}}
      - -X github.com/pomerium/pomerium/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/pomerium/pomerium/internal/version.BuildMeta={{.Timestamp}}
      - -X github.com/pomerium/pomerium/internal/version.ProjectName=pomerium
      - -X github.com/pomerium/pomerium/internal/version.ProjectURL=https://wwww.pomerium.io

  - id: pomerium-cli
    main: cmd/pomerium-cli/cli.go
    binary: pomerium-cli
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm

    ldflags:
      - -s -w
      - -X github.com/pomerium/pomerium/internal/version.Version={{.Version}}
      - -X github.com/pomerium/pomerium/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/pomerium/pomerium/internal/version.BuildMeta={{.Timestamp}}
      - -X github.com/pomerium/pomerium/internal/version.ProjectName=pomerium
      - -X github.com/pomerium/pomerium/internal/version.ProjectURL=https://wwww.pomerium.io

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - pomerium
      - pomerium-cli
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}+next"

dockers:
  - image_templates:
      - "pomerium/pomerium:{{ .Tag }}"
    dockerfile: .github/Dockerfile-release
    binaries:
      - pomerium
      - pomerium-cli
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"

  - goarch: arm64
    image_templates:
      - "pomerium/pomerium:arm64v8-{{ .Tag }}"
    dockerfile: .github/Dockerfile-release.arm64v8
    binaries:
      - pomerium
      - pomerium-cli
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"

  - goarch: arm
    goarm: 7
    image_templates:
      - "pomerium/pomerium:arm32v7-{{ .Tag }}"
    dockerfile: .github/Dockerfile-release.arm32v7
    binaries:
      - pomerium
      - pomerium-cli

    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"

  - goarch: arm
    goarm: 6
    image_templates:
      - "pomerium/pomerium:arm32v6-{{ .Tag }}"
    dockerfile: .github/Dockerfile-release.arm32v6
    binaries:
      - pomerium
      - pomerium-cli
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"
