codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: .2
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
