### Other keys configuration removed for clarity ###

# Proxied routes and per-route policies are defined in a policy block
policy: # Omit the 'policy' key if you are encoding it into an environment variable
  - from: httpbin.corp.beyondperimeter.com
    to: http://localhost:8000
    allowed_domains:
      - pomerium.io
    cors_allow_preflight: true
    timeout: 30s
  - from: external-httpbin.corp.beyondperimeter.com
    to: httpbin.org
    allowed_domains:
      - gmail.com
  - from: weirdlyssl.corp.beyondperimeter.com
    to: http://neverssl.com
    allowed_users:
      - bdd@pomerium.io
    allowed_groups:
      - admins
      - developers
  - from: hello.corp.beyondperimeter.com
    to: http://localhost:8080
    allowed_groups:
      - admins@pomerium.io