{{- if .Values.omnibusMode -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "pomerium.name" . }}
    chart: {{ template "pomerium.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "pomerium.fullname" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pomerium.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "pomerium.name" . }}
        chart: {{ template "pomerium.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
{{- range $key, $value := .Values.extraArgs }}
{{- if $value }}
          - --{{ $key }}={{ $value }}
{{- else }}
          - --{{ $key }}
{{- end }}
{{- end }}
        env:
        - name: SERVICES
          value: all
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "pomerium.fullname" . }}
              key: cookie-secret
        - name: SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "pomerium.fullname" . }}
              key: shared-secret
        - name: AUTHENTICATE_SERVICE_URL
          value: {{ .Values.proxy.authenticateServiceUrl }}
        - name: AUTHORIZE_SERVICE_URL
          value: {{ .Values.proxy.authorizeServiceUrl }}
        - name: REDIRECT_URL
          value: {{ .Values.authenticate.redirectUrl }}
        - name: PROXY_ROOT_DOMAIN
          value: {{ .Values.authenticate.proxyRootDomains }}
        - name: IDP_PROVIDER
          value: {{ .Values.authenticate.idp.provider }}
        - name: IDP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  {{ template "pomerium.fullname" . }}
              key: idp-client-id
        - name: IDP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  {{ template "pomerium.fullname" . }}
              key: idp-client-secret
{{- if .Values.authenticate.idp.url }}
        - name: IDP_PROVIDER_URL
          value: {{ .Values.authenticate.idp.url }}
{{- end }}
{{- if .Values.config.policyFile }}
        - name: POLICY_FILE
          value: /etc/pomerium/policy.yaml
{{- end }}
{{- if .Values.config.policy}}
        - name: POLICY
          value: {{ .Values.config.policy }}
{{- end }}
{{- if .Values.config.cert }}
        - name: CERTIFICATE
          valueFrom:
            secretKeyRef:
              name: {{ template "pomerium.fullname" . }}
              key: certificate
{{- end }}
{{- if .Values.config.key }}
        - name: CERTIFICATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "pomerium.fullname" . }}
              key: certificate-key
{{- end }}
{{- if .Values.config.ca }}
        - name: CERTIFICATE_AUTHORITY
          valueFrom:
            secretKeyRef:
              name: {{ template "pomerium.fullname" . }}
              key: certificate-authority
{{- end }}
{{- range $name, $value := .Values.extraEnv }}
        - name: {{ $name }}
          value: {{ quote $value }}
{{- end }}
        ports:
          - containerPort: 443
            name: https
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: https
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /ping
            port: https
            scheme: HTTPS
      
        volumeMounts:
        - mountPath: /etc/pomerium/
          name: {{ template "pomerium.fullname" . }}-policy
     
      volumes:
      - name: {{ template "pomerium.fullname" . }}-policy
        configMap:
          name: {{ template "pomerium.fullname" . }}
      
      resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.extraVolumes }}
      volumes:
{{- toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- end -}}