{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "pomerium.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pomerium.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "pomerium.chart" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - secretName: {{ default .Values.ingress.secretName .Values.ingress.secret.name}}
      hosts:
        {{- range .Values.config.policyFile }}
        - {{ .from }}
        {{- end }}
        - {{ .Values.authorize.name }}.{{ .Values.config.rootDomain }}
        - {{ .Values.authenticate.name }}.{{ .Values.config.rootDomain }}
  rules:
    {{- $proxyService := printf "%s-%s" (include "pomerium.fullname" .)  .Values.proxy.name }}
    {{- range .Values.config.policyFile }}
    - host: {{ .from }}
      http:
        paths:
          - paths:
            backend:
              serviceName: {{ $proxyService }}
              servicePort: https
    {{- end }}
    - host: {{ .Values.authorize.name }}.{{ .Values.config.rootDomain }}
      http:
        paths:
          - paths:
            backend:
              serviceName: {{ include "pomerium.fullname" .}}-{{ .Values.authorize.name }}
              servicePort: https
    - host: {{ .Values.authenticate.name }}.{{ .Values.config.rootDomain }}
      http:
        paths:
          - paths:
            backend:
              serviceName: {{ include "pomerium.fullname" .}}-{{ .Values.authenticate.name }}
              servicePort: https
{{- end }}