apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "pomerium.name" . }}
    chart: {{ template "pomerium.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "pomerium.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if or (eq .Values.config.services "authenticate") (eq .Values.config.services "all") }}
  idp-client-id: {{ .Values.authenticate.idp.clientID | b64enc | quote }}
  idp-client-secret: {{ .Values.authenticate.idp.clientSecret | b64enc | quote }}
{{- end }}
  cookie-secret: {{ .Values.config.cookieSecret | b64enc | quote }}
  shared-secret: {{ .Values.config.sharedSecret | b64enc | quote }}
{{- if .Values.config.cert }}
  certificate: {{ .Values.config.cert | b64enc | quote }}
{{- end }}
{{- if .Values.config.key }}
  certificate-key: {{ .Values.config.key | b64enc | quote }}
{{- end }}
{{- if .Values.config.ca }}
  certificate-authority: {{ .Values.config.ca | b64enc | quote }}
{{- end }}
