apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "pomerium.name" . }}
    chart: {{ template "pomerium.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "pomerium.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cookie-secret: {{ .Values.config.cookieSecret | b64enc | quote }}
  shared-secret: {{ .Values.config.sharedSecret | b64enc | quote }}
  idp-client-id: {{ .Values.authenticate.idp.clientID | b64enc | quote }}
  idp-client-secret: {{ .Values.authenticate.idp.clientSecret | b64enc | quote }}
  certificate: {{- if .Values.config.cert }} {{ .Values.config.cert | b64enc | quote }} {{- end }}
  certificate-key: {{- if .Values.config.key }} {{ .Values.config.key | b64enc | quote }} {{- end }}
  certificate-authority: {{- if .Values.config.ca }} {{ .Values.config.ca | b64enc | quote }} {{- end }}
