{{- if .Values.ingress.enabled }}
{{- if not .Values.ingress.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "pomerium-tls" .Values.ingress.secret.name }}
  labels:
    app: {{ template "pomerium.name" . }}
    chart: {{ template "pomerium.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.secret.cert }}
  tls.key: {{ .Values.ingress.secret.key }}
---
{{- end }}
{{- end }}
