---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pomerium-zero
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - patch
    resourceNames:
      - pomerium
