/**
 * Client-certificate helpers for the downstream mTLS e2e suite.
 * Adapted from internal/acceptance/browser/helpers/mtls.ts for the
 * containerized runner (cert locations come from CERTS_DIR).
 */

import { Browser, BrowserContext } from "@playwright/test";
import * as path from "path";

/** Client certificate types generated by scripts/gen-certs.sh. */
export type ClientCertType =
  | "valid" // signed by the trusted root CA
  | "chain" // signed by the intermediate CA (depth > 1)
  | "wrong-ca"; // signed by an untrusted CA

const CERTS_DIR = process.env.CERTS_DIR ?? "/certs/mtls";

export function certPaths(certType: ClientCertType): {
  certPath: string;
  keyPath: string;
} {
  switch (certType) {
    case "valid":
      return {
        certPath: path.join(CERTS_DIR, "client-valid.crt"),
        keyPath: path.join(CERTS_DIR, "client-valid.key"),
      };
    case "chain":
      return {
        certPath: path.join(CERTS_DIR, "client-chain-full.crt"),
        keyPath: path.join(CERTS_DIR, "client-chain.key"),
      };
    case "wrong-ca":
      return {
        certPath: path.join(CERTS_DIR, "client-wrong-ca.crt"),
        keyPath: path.join(CERTS_DIR, "client-wrong-ca.key"),
      };
  }
}

/**
 * Create a browser context that presents the given client certificate to the
 * given origin. The origin must match scheme, host AND port exactly
 * (e.g. https://mtls.localhost.pomerium.io:8443).
 */
export async function newContextWithCert(
  browser: Browser,
  certType: ClientCertType,
  originUrl: string
): Promise<BrowserContext> {
  const { certPath, keyPath } = certPaths(certType);
  return browser.newContext({
    ignoreHTTPSErrors: true,
    clientCertificates: [
      {
        origin: new URL(originUrl).origin,
        certPath,
        keyPath,
      },
    ],
  });
}

/** Create a browser context without any client certificate. */
export async function newContextWithoutCert(browser: Browser): Promise<BrowserContext> {
  return browser.newContext({
    ignoreHTTPSErrors: true,
  });
}

/**
 * Reserved for future `enforcement: reject_connection` specs, where the TLS
 * handshake itself fails and page.goto rejects with net::ERR_SSL_CLIENT_AUTH_*
 * errors. Under the default policy_with_default_deny mode the handshake always
 * succeeds and denials arrive as HTTP 495 responses instead.
 */
export function isTLSHandshakeError(err: unknown): boolean {
  const msg = err instanceof Error ? err.message : String(err);
  return /SSL|TLS|certificate|handshake/i.test(msg);
}
