package mcp

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"sync/atomic"
	"time"

	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"golang.org/x/sync/singleflight"
	googlegrpc "google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"

	"github.com/pomerium/pomerium/config"
	"github.com/pomerium/pomerium/internal/log"
	"github.com/pomerium/pomerium/internal/mcp/extproc"
	oauth21proto "github.com/pomerium/pomerium/internal/oauth21/gen"
	"github.com/pomerium/pomerium/pkg/cryptutil"
	"github.com/pomerium/pomerium/pkg/grpc"
	"github.com/pomerium/pomerium/pkg/grpc/databroker"
	"github.com/pomerium/pomerium/pkg/telemetry/trace"
)

const (
	// pendingAuthExpiry is the maximum lifetime for pending upstream authorization state.
	pendingAuthExpiry = 5 * time.Minute
)

// newPendingUpstreamAuthParams holds the call-site-specific values for creating
// a PendingUpstreamAuth. PKCE and state must be generated by the caller since
// they can fail; the constructor assembles the rest deterministically.
type newPendingUpstreamAuthParams struct {
	StateID     string
	UserID      string
	RouteID     string
	UpstreamURL string // base upstream URL for token storage keys
	OriginalURL string // full request URL (may differ from UpstreamURL in ext_proc path)
	Host        string // downstream host (with optional port)
	AuthReqID   string // only set by connect/authorize path
	Verifier    string
	Challenge   string
}

func newPendingUpstreamAuth(p newPendingUpstreamAuthParams, setup *upstreamOAuthSetupResult) *oauth21proto.PendingUpstreamAuth {
	now := time.Now()
	return &oauth21proto.PendingUpstreamAuth{
		StateId:                   p.StateID,
		UserId:                    p.UserID,
		RouteId:                   p.RouteID,
		UpstreamServer:            p.UpstreamURL,
		PkceVerifier:              p.Verifier,
		PkceChallenge:             p.Challenge,
		Scopes:                    setup.Scopes,
		AuthorizationEndpoint:     setup.Discovery.AuthorizationEndpoint,
		TokenEndpoint:             setup.Discovery.TokenEndpoint,
		AuthorizationServerIssuer: setup.Discovery.Issuer,
		OriginalUrl:               p.OriginalURL,
		RedirectUri:               setup.RedirectURI,
		ClientId:                  setup.ClientID,
		ClientSecret:              setup.ClientSecret,
		DownstreamHost:            p.Host,
		AuthReqId:                 p.AuthReqID,
		CreatedAt:                 timestamppb.New(now),
		ExpiresAt:                 timestamppb.New(now.Add(pendingAuthExpiry)),
		ResourceParam:             setup.Discovery.Resource,
	}
}

// UpstreamAuthHandler implements extproc.UpstreamRequestHandler for MCP upstream OAuth flows.
// It handles token injection on the request path and 401/403 interception on the response path.
// All upstream auth modes (auto-discovery, pre-registered, fully static) use a unified
// UpstreamMCPToken storage path.
//
// hosts and asMetadataDomainMatcher refresh via OnConfigChange; both are held
// behind atomic pointers so request-path readers stay lock-free.
type UpstreamAuthHandler struct {
	storage                 HandlerStorage
	hosts                   *HostInfo
	httpClient              *http.Client
	asMetadataDomainMatcher atomic.Pointer[DomainMatcher]
	singleFlight            singleflight.Group
}

// NewUpstreamAuthHandler creates a new UpstreamAuthHandler.
func NewUpstreamAuthHandler(
	storage HandlerStorage,
	hosts *HostInfo,
	httpClient *http.Client,
	asMetadataDomainMatcher *DomainMatcher,
) *UpstreamAuthHandler {
	h := &UpstreamAuthHandler{
		storage:    storage,
		hosts:      hosts,
		httpClient: httpClient,
	}
	h.asMetadataDomainMatcher.Store(asMetadataDomainMatcher)
	return h
}

// OnConfigChange refreshes the handler's host index and AS-metadata domain allowlist
// so that config updates delivered after the handler was constructed become visible
// to ext_proc lookups.
func (h *UpstreamAuthHandler) OnConfigChange(cfg *config.Config) {
	h.hosts.OnConfigChange(cfg)
	var allowed []string
	if cfg != nil {
		allowed = cfg.Options.GetMCPAllowedAsMetadataDomains()
	}
	h.asMetadataDomainMatcher.Store(NewDomainMatcher(allowed))
}

// NewUpstreamAuthHandlerFromConfig creates an UpstreamAuthHandler using the provided config
// and outbound gRPC connection. This is the primary factory used by the controlplane server.
func NewUpstreamAuthHandlerFromConfig(
	ctx context.Context,
	cfg *config.Config,
	outboundGrpcConn *grpc.CachedOutboundGRPClientConn,
) (*UpstreamAuthHandler, error) {
	tracerProvider := trace.NewTracerProvider(ctx, "MCP-ExtProc")

	sharedKey, err := cfg.Options.GetSharedKey()
	if err != nil {
		return nil, fmt.Errorf("shared key: %w", err)
	}

	dataBrokerConn, err := outboundGrpcConn.Get(ctx, &grpc.OutboundOptions{
		OutboundPort:   cfg.OutboundPort,
		InstallationID: cfg.Options.InstallationID,
		ServiceName:    cfg.Options.Services,
		SignedJWTKey:   sharedKey,
	}, googlegrpc.WithStatsHandler(otelgrpc.NewClientHandler(otelgrpc.WithTracerProvider(tracerProvider))))
	if err != nil {
		return nil, fmt.Errorf("databroker connection: %w", err)
	}

	storage := NewStorage(databroker.NewDataBrokerServiceClient(dataBrokerConn))

	httpClient := http.DefaultClient
	if cfg.Options.CA != "" || cfg.Options.CAFile != "" {
		rootCAs, caErr := cryptutil.GetCertPool(cfg.Options.CA, cfg.Options.CAFile)
		if caErr != nil {
			log.Ctx(ctx).Warn().Err(caErr).Msg("mcp_upstream_auth: error loading custom CA, using system defaults")
		} else {
			transport := http.DefaultTransport.(*http.Transport).Clone()
			transport.TLSClientConfig = &tls.Config{
				RootCAs:    rootCAs,
				MinVersion: tls.VersionTLS12,
			}
			httpClient = &http.Client{Transport: transport}
		}
	}

	hosts := NewHostInfo(cfg, httpClient)
	asDomainMatcher := NewDomainMatcher(cfg.Options.GetMCPAllowedAsMetadataDomains())

	return NewUpstreamAuthHandler(storage, hosts, httpClient, asDomainMatcher), nil
}

// GetUpstreamToken looks up a cached upstream token for the given route context and host.
// Uses a unified UpstreamMCPToken storage for all routes (static, pre-registered, and auto-discovery).
// Returns empty string if no token is available.
func (h *UpstreamAuthHandler) GetUpstreamToken(
	ctx context.Context,
	routeCtx *extproc.RouteContext,
	host string,
) (string, error) {
	hostname := stripPort(host)

	info, ok := h.hosts.GetServerHostInfo(hostname)
	if !ok || info.UpstreamURL == "" {
		log.Ctx(ctx).Debug().
			Str("route_id", routeCtx.RouteID).
			Str("user_id", routeCtx.UserID).
			Str("downstream_host", host).
			Str("hostname", hostname).
			Bool("host_info_found", ok).
			Msg("mcp_upstream_auth: no host info for upstream token lookup")
		return "", nil
	}

	userID := routeCtx.UserID
	if userID == "" {
		log.Ctx(ctx).Debug().
			Str("route_id", routeCtx.RouteID).
			Str("downstream_host", host).
			Str("upstream_server", info.UpstreamURL).
			Msg("mcp_upstream_auth: no user ID in route context, skipping token injection")
		return "", nil
	}
	token, err := h.storage.GetUpstreamMCPToken(ctx, userID, routeCtx.RouteID, info.UpstreamURL)
	if err != nil {
		if isNotFound(err) {
			log.Ctx(ctx).Debug().
				Str("route_id", routeCtx.RouteID).
				Str("user_id", userID).
				Str("downstream_host", host).
				Str("upstream_server", info.UpstreamURL).
				Msg("mcp_upstream_auth: no cached upstream token found")
			return "", nil
		}
		return "", fmt.Errorf("looking up upstream token: %w", err)
	}

	event := log.Ctx(ctx).Debug().
		Str("route_id", routeCtx.RouteID).
		Str("user_id", userID).
		Str("downstream_host", host).
		Str("upstream_server", info.UpstreamURL).
		Bool("has_refresh_token", token.RefreshToken != "")
	if token.ExpiresAt != nil {
		event.Time("expires_at", token.ExpiresAt.AsTime())
	}
	event.Msg("mcp_upstream_auth: loaded cached upstream token")

	// Check if access token is expired
	if token.ExpiresAt != nil && token.ExpiresAt.AsTime().Before(time.Now()) {
		log.Ctx(ctx).Debug().
			Str("route_id", routeCtx.RouteID).
			Str("user_id", userID).
			Str("upstream_server", info.UpstreamURL).
			Bool("has_refresh_token", token.RefreshToken != "").
			Bool("has_token_endpoint", token.TokenEndpoint != "").
			Time("expires_at", token.ExpiresAt.AsTime()).
			Msg("mcp_upstream_auth: cached upstream token expired, attempting refresh or clear")
		// Read client_secret from config (single source of truth) rather than from
		// the stored token, to avoid replicating the shared credential per-user.
		var configClientSecret string
		if info.UpstreamOAuth2 != nil {
			configClientSecret = info.UpstreamOAuth2.ClientSecret
		}
		return h.refreshOrClearToken(ctx, token, userID, routeCtx.RouteID, info.UpstreamURL, configClientSecret)
	}

	log.Ctx(ctx).Debug().
		Str("route_id", routeCtx.RouteID).
		Str("user_id", userID).
		Str("upstream_server", info.UpstreamURL).
		Msg("mcp_upstream_auth: returning cached upstream access token")

	return token.AccessToken, nil
}

// refreshOrClearToken attempts to refresh an expired token. On permanent failure (4xx) or no refresh
// capability, it clears the cached token and returns empty. On transient failure (5xx, network),
// it preserves the token and returns an error.
func (h *UpstreamAuthHandler) refreshOrClearToken(
	ctx context.Context,
	token *oauth21proto.UpstreamMCPToken,
	userID, routeID, upstreamServer string,
	configClientSecret string,
) (string, error) {
	// Try refresh if we have a refresh token and token endpoint.
	// Uses singleflight to deduplicate concurrent refresh requests.
	if token.RefreshToken != "" && token.TokenEndpoint != "" {
		sfKey := fmt.Sprintf("mcp:%s:%s:%s", userID, routeID, upstreamServer)
		result, err, _ := h.singleFlight.Do(sfKey, func() (any, error) {
			return h.refreshToken(ctx, token, configClientSecret)
		})
		if err != nil {
			if isTokenRefreshPermanent(err) {
				// 4xx from token endpoint: the refresh token is invalid/revoked.
				// Delete the cached token so the next 401 from upstream triggers re-auth.
				log.Ctx(ctx).Warn().Err(err).
					Str("user_id", userID).
					Str("route_id", routeID).
					Msg("mcp_upstream_auth: refresh token rejected by AS, clearing cached token")
				if delErr := h.storage.DeleteUpstreamMCPToken(ctx, userID, routeID, upstreamServer); delErr != nil {
					log.Ctx(ctx).Error().Err(delErr).Msg("mcp_upstream_auth: failed to delete stale token after refresh failure")
				}
				return "", nil
			}
			// Transient failure (network error, 5xx, etc.): preserve the cached token
			// and return an error so ext_proc returns 502 rather than silently dropping auth.
			log.Ctx(ctx).Warn().Err(err).
				Str("user_id", userID).
				Str("route_id", routeID).
				Str("upstream_server", upstreamServer).
				Msg("mcp_upstream_auth: transient upstream token refresh failure, preserving cached token")
			return "", fmt.Errorf("refreshing upstream token: %w", err)
		}
		refreshed := result.(*oauth21proto.UpstreamMCPToken)
		event := log.Ctx(ctx).Debug().
			Str("user_id", userID).
			Str("route_id", routeID).
			Str("upstream_server", upstreamServer)
		if refreshed.ExpiresAt != nil {
			event.Time("expires_at", refreshed.ExpiresAt.AsTime())
		}
		event.Msg("mcp_upstream_auth: refreshed upstream token successfully")
		return refreshed.AccessToken, nil
	}

	// Expired with no refresh token - clear it.
	log.Ctx(ctx).Debug().
		Str("user_id", userID).
		Str("route_id", routeID).
		Str("upstream_server", upstreamServer).
		Bool("has_refresh_token", token.RefreshToken != "").
		Bool("has_token_endpoint", token.TokenEndpoint != "").
		Msg("mcp_upstream_auth: upstream token expired with no refresh token, clearing")
	if delErr := h.storage.DeleteUpstreamMCPToken(ctx, userID, routeID, upstreamServer); delErr != nil {
		log.Ctx(ctx).Error().Err(delErr).Msg("mcp_upstream_auth: failed to delete expired token")
	}

	return "", nil
}

// HandleUpstreamResponse processes a 401/403 response from upstream.
// For 401: runs discovery, generates PKCE, stores pending auth state, returns 401 action.
// For 403 with insufficient_scope: similar but with expanded scopes.
// Returns nil if the response should be passed through.
func (h *UpstreamAuthHandler) HandleUpstreamResponse(
	ctx context.Context,
	routeCtx *extproc.RouteContext,
	host, originalURL string,
	statusCode int,
	wwwAuthenticate string,
) (*extproc.UpstreamAuthAction, error) {
	hostname := stripPort(host)

	info, ok := h.hosts.GetServerHostInfo(hostname)
	if !ok || info.UpstreamURL == "" {
		log.Ctx(ctx).Debug().
			Str("route_id", routeCtx.RouteID).
			Str("user_id", routeCtx.UserID).
			Str("downstream_host", host).
			Str("hostname", hostname).
			Bool("host_info_found", ok).
			Int("status_code", statusCode).
			Msg("mcp_upstream_auth: no host info for upstream response handling")
		return nil, nil
	}

	wwwAuth := ParseWWWAuthenticate(wwwAuthenticate)

	switch statusCode {
	case 401:
		return h.handle401(ctx, routeCtx, host, hostname, originalURL, wwwAuth)
	case 403:
		if wwwAuth != nil && wwwAuth.Error == "insufficient_scope" {
			return h.handle401(ctx, routeCtx, host, hostname, originalURL, wwwAuth)
		}
		return nil, nil
	default:
		return nil, nil
	}
}

// handle401 handles a 401 (or 403 insufficient_scope) from upstream by running discovery,
// storing pending auth state with an index, and returning a 401 action for the MCP client.
func (h *UpstreamAuthHandler) handle401(
	ctx context.Context,
	routeCtx *extproc.RouteContext,
	host, hostname, originalURL string,
	wwwAuth *WWWAuthenticateParams,
) (*extproc.UpstreamAuthAction, error) {
	userID := routeCtx.UserID
	if userID == "" {
		log.Ctx(ctx).Warn().
			Msg("mcp_upstream_auth: no user ID in route context, passing through 401")
		return nil, nil
	}

	serverInfo, err := h.getServerInfo(hostname)
	if err != nil {
		return nil, fmt.Errorf("getting server info: %w", err)
	}

	// The resource URL is the actual URL the client was trying to access (with path).
	// This is used for PRM discovery/validation and the OAuth resource parameter.
	// The base upstreamServer URL is used for token storage keys (must match GetUpstreamToken).
	resourceURL := stripQueryFromURL(originalURL)

	setupOpts := []UpstreamOAuthSetupOption{
		WithWWWAuthenticate(wwwAuth),
		WithFallbackAuthorizationURL(serverInfo.AuthorizationServerURL),
		WithASMetadataDomainMatcher(h.asMetadataDomainMatcher.Load()),
		WithAllowDCRFallback(true),
	}
	setupOpts = append(setupOpts, upstreamOAuthSetupOptsFromConfig(serverInfo.UpstreamOAuth2)...)
	setup, err := runUpstreamOAuthSetup(ctx, h.httpClient, resourceURL, host, setupOpts...)
	if err != nil {
		return nil, fmt.Errorf("upstream OAuth setup: %w", err)
	}
	if setup == nil {
		return nil, nil
	}

	// Generate PKCE
	verifier, challenge, err := generatePKCE()
	if err != nil {
		return nil, fmt.Errorf("generating PKCE: %w", err)
	}

	// Generate state
	stateID, err := generateRandomString(32)
	if err != nil {
		return nil, fmt.Errorf("generating state: %w", err)
	}

	// Store pending authorization.
	// UpstreamServer uses the base URL for consistent token storage keys.
	pending := newPendingUpstreamAuth(newPendingUpstreamAuthParams{
		StateID:     stateID,
		UserID:      userID,
		RouteID:     routeCtx.RouteID,
		UpstreamURL: serverInfo.UpstreamURL,
		OriginalURL: originalURL,
		Host:        host,
		Verifier:    verifier,
		Challenge:   challenge,
	}, setup)

	if err := h.storage.PutPendingUpstreamAuth(ctx, pending); err != nil {
		return nil, fmt.Errorf("storing pending auth: %w", err)
	}

	// Return 401 with Pomerium's own PRM so the MCP client re-runs its auth flow.
	// Extract the request path from originalURL so the resource_metadata URI
	// matches the path-based well-known endpoint (RFC 9728 §4).
	var requestPath string
	if parsed, err := url.Parse(originalURL); err == nil {
		requestPath = parsed.Path
	}

	return &extproc.UpstreamAuthAction{
		WWWAuthenticate: fmt.Sprintf(`Bearer resource_metadata="%s"`, ProtectedResourceMetadataURL(host, requestPath)),
	}, nil
}

// refreshToken attempts to refresh an expired upstream token.
// configClientSecret is the client_secret from route config (single source of truth
// for pre-registered clients). It is passed in rather than read from the stored token
// to avoid replicating the shared admin credential in every per-user token record.
func (h *UpstreamAuthHandler) refreshToken(
	ctx context.Context,
	token *oauth21proto.UpstreamMCPToken,
	configClientSecret string,
) (*oauth21proto.UpstreamMCPToken, error) {
	// Use ResourceParam for the RFC 8707 resource indicator.
	// Falls back to UpstreamServer for tokens stored before ResourceParam was added.
	resourceParam := token.GetResourceParam()
	if resourceParam == "" {
		resourceParam = token.UpstreamServer
	}
	data := url.Values{
		"grant_type":    {"refresh_token"},
		"refresh_token": {token.RefreshToken},
		"client_id":     {token.ClientId},
	}
	if configClientSecret != "" {
		data.Set("client_secret", configClientSecret)
	}
	if resourceParam != "" {
		data.Set("resource", resourceParam)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, token.TokenEndpoint, strings.NewReader(data.Encode()))
	if err != nil {
		return nil, fmt.Errorf("creating refresh request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	tokenResp, err := exchangeToken(h.httpClient, req)
	if err != nil {
		return nil, fmt.Errorf("token refresh: %w", err)
	}

	// Update token in storage
	now := time.Now()
	refreshedToken := &oauth21proto.UpstreamMCPToken{
		UserId:                    token.UserId,
		RouteId:                   token.RouteId,
		UpstreamServer:            token.UpstreamServer,
		AccessToken:               tokenResp.AccessToken,
		RefreshToken:              tokenResp.RefreshToken,
		TokenType:                 tokenResp.TokenType,
		IssuedAt:                  timestamppb.New(now),
		Scopes:                    token.Scopes,
		ClientId:                  token.ClientId,
		AuthorizationServerIssuer: token.AuthorizationServerIssuer,
		TokenEndpoint:             token.TokenEndpoint,
		ResourceParam:             token.ResourceParam,
	}

	if tokenResp.ExpiresIn > 0 {
		refreshedToken.ExpiresAt = timestamppb.New(now.Add(time.Duration(tokenResp.ExpiresIn) * time.Second))
	}

	// Preserve old refresh token if the AS didn't rotate it
	if refreshedToken.RefreshToken == "" {
		refreshedToken.RefreshToken = token.RefreshToken
	}

	if err := h.storage.PutUpstreamMCPToken(ctx, refreshedToken); err != nil {
		return nil, fmt.Errorf("storing refreshed token: %w", err)
	}

	return refreshedToken, nil
}

func (h *UpstreamAuthHandler) getServerInfo(hostname string) (ServerHostInfo, error) {
	info, ok := h.hosts.GetServerHostInfo(hostname)
	if !ok {
		return ServerHostInfo{}, fmt.Errorf("no server info for host %s", hostname)
	}
	if info.UpstreamURL == "" {
		return ServerHostInfo{}, fmt.Errorf("no upstream URL configured for host %s", hostname)
	}
	return info, nil
}

func isNotFound(err error) bool {
	return status.Code(err) == codes.NotFound
}

// isTokenRefreshPermanent reports whether a token refresh error indicates a permanent
// failure (the refresh token is invalid/revoked and should be discarded).
// HTTP 4xx responses from the token endpoint are permanent: the AS is rejecting the request.
// Everything else (network errors, 5xx, parse errors) is transient.
func isTokenRefreshPermanent(err error) bool {
	var tokenErr *tokenEndpointError
	if errors.As(err, &tokenErr) {
		return tokenErr.StatusCode >= 400 && tokenErr.StatusCode < 500
	}
	return false
}
