// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: recording.proto

package recording

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordingData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*RecordingData_Metadata
	//	*RecordingData_Chunk
	//	*RecordingData_Checksum
	Data          isRecordingData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingData) Reset() {
	*x = RecordingData{}
	mi := &file_recording_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingData) ProtoMessage() {}

func (x *RecordingData) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingData.ProtoReflect.Descriptor instead.
func (*RecordingData) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{0}
}

func (x *RecordingData) GetData() isRecordingData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecordingData) GetMetadata() *RecordingMetadata {
	if x != nil {
		if x, ok := x.Data.(*RecordingData_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *RecordingData) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*RecordingData_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *RecordingData) GetChecksum() []byte {
	if x != nil {
		if x, ok := x.Data.(*RecordingData_Checksum); ok {
			return x.Checksum
		}
	}
	return nil
}

type isRecordingData_Data interface {
	isRecordingData_Data()
}

type RecordingData_Metadata struct {
	Metadata *RecordingMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type RecordingData_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type RecordingData_Checksum struct {
	Checksum []byte `protobuf:"bytes,3,opt,name=checksum,proto3,oneof"`
}

func (*RecordingData_Metadata) isRecordingData_Data() {}

func (*RecordingData_Chunk) isRecordingData_Data() {}

func (*RecordingData_Checksum) isRecordingData_Data() {}

type RecordingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      *anypb.Any             `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingMetadata) Reset() {
	*x = RecordingMetadata{}
	mi := &file_recording_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingMetadata) ProtoMessage() {}

func (x *RecordingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_recording_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingMetadata.ProtoReflect.Descriptor instead.
func (*RecordingMetadata) Descriptor() ([]byte, []int) {
	return file_recording_proto_rawDescGZIP(), []int{1}
}

func (x *RecordingMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordingMetadata) GetMetadata() *anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_recording_proto protoreflect.FileDescriptor

const file_recording_proto_rawDesc = "" +
	"\n" +
	"\x0frecording.proto\x12\trecording\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n" +
	"\rRecordingData\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1c.recording.RecordingMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunk\x12\x1c\n" +
	"\bchecksum\x18\x03 \x01(\fH\x00R\bchecksumB\x06\n" +
	"\x04data\"U\n" +
	"\x11RecordingMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\bmetadata2P\n" +
	"\x10RecordingService\x12<\n" +
	"\x06Record\x12\x18.recording.RecordingData\x1a\x16.google.protobuf.Empty(\x01B1Z/github.com/pomerium/pomerium/pkg/grpc/recordingb\x06proto3"

var (
	file_recording_proto_rawDescOnce sync.Once
	file_recording_proto_rawDescData []byte
)

func file_recording_proto_rawDescGZIP() []byte {
	file_recording_proto_rawDescOnce.Do(func() {
		file_recording_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recording_proto_rawDesc), len(file_recording_proto_rawDesc)))
	})
	return file_recording_proto_rawDescData
}

var file_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recording_proto_goTypes = []any{
	(*RecordingData)(nil),     // 0: recording.RecordingData
	(*RecordingMetadata)(nil), // 1: recording.RecordingMetadata
	(*anypb.Any)(nil),         // 2: google.protobuf.Any
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_recording_proto_depIdxs = []int32{
	1, // 0: recording.RecordingData.metadata:type_name -> recording.RecordingMetadata
	2, // 1: recording.RecordingMetadata.metadata:type_name -> google.protobuf.Any
	0, // 2: recording.RecordingService.Record:input_type -> recording.RecordingData
	3, // 3: recording.RecordingService.Record:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recording_proto_init() }
func file_recording_proto_init() {
	if File_recording_proto != nil {
		return
	}
	file_recording_proto_msgTypes[0].OneofWrappers = []any{
		(*RecordingData_Metadata)(nil),
		(*RecordingData_Chunk)(nil),
		(*RecordingData_Checksum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recording_proto_rawDesc), len(file_recording_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recording_proto_goTypes,
		DependencyIndexes: file_recording_proto_depIdxs,
		MessageInfos:      file_recording_proto_msgTypes,
	}.Build()
	File_recording_proto = out.File
	file_recording_proto_goTypes = nil
	file_recording_proto_depIdxs = nil
}
