// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payload.proto

package opaquetoken

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type distinguishes what a token may be presented for. It is checked when the
// token is opened, so a token minted for one purpose cannot be replayed as
// another.
//
// Values are part of the token wire format and must never be renumbered.
type Type int32

const (
	Type_TYPE_UNSPECIFIED   Type = 0
	Type_TYPE_AUTHORIZATION Type = 1
	Type_TYPE_ACCESS        Type = 2
	Type_TYPE_REFRESH       Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_AUTHORIZATION",
		2: "TYPE_ACCESS",
		3: "TYPE_REFRESH",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":   0,
		"TYPE_AUTHORIZATION": 1,
		"TYPE_ACCESS":        2,
		"TYPE_REFRESH":       3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_payload_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{0}
}

// Payload is the sealed contents of an opaque token: a reference to a
// databroker record, together with the metadata needed to validate that
// reference.
//
// Field numbers are part of the token wire format and must never be
// renumbered: tokens minted by earlier builds are still presented to newer
// ones.
type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the id of the databroker record this token dereferences to.
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Type      Type                   `protobuf:"varint,3,opt,name=type,proto3,enum=opaquetoken.Type" json:"type,omitempty"`
	// record_version is the databroker record version of the record referenced by
	// this token, captured at issuance time. The authorize service replays it as a
	// minimum-version hint when reading that record, providing read-your-writes
	// across databroker replicas. Zero means no hint.
	RecordVersion uint64 `protobuf:"varint,4,opt,name=record_version,json=recordVersion,proto3" json:"record_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Payload) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *Payload) GetRecordVersion() uint64 {
	if x != nil {
		return x.RecordVersion
	}
	return 0
}

var File_payload_proto protoreflect.FileDescriptor

const file_payload_proto_rawDesc = "" +
	"\n" +
	"\rpayload.proto\x12\vopaquetoken\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\aPayload\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x02id\x12A\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.opaquetoken.TypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x04type\x12%\n" +
	"\x0erecord_version\x18\x04 \x01(\x04R\rrecordVersion*W\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TYPE_AUTHORIZATION\x10\x01\x12\x0f\n" +
	"\vTYPE_ACCESS\x10\x02\x12\x10\n" +
	"\fTYPE_REFRESH\x10\x03B\x9e\x01\n" +
	"\x0fcom.opaquetokenB\fPayloadProtoP\x01Z1github.com/pomerium/pomerium/internal/opaquetoken\xa2\x02\x03OXX\xaa\x02\vOpaquetoken\xca\x02\vOpaquetoken\xe2\x02\x17Opaquetoken\\GPBMetadata\xea\x02\vOpaquetokenb\x06proto3"

var (
	file_payload_proto_rawDescOnce sync.Once
	file_payload_proto_rawDescData []byte
)

func file_payload_proto_rawDescGZIP() []byte {
	file_payload_proto_rawDescOnce.Do(func() {
		file_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)))
	})
	return file_payload_proto_rawDescData
}

var file_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payload_proto_goTypes = []any{
	(Type)(0),                     // 0: opaquetoken.Type
	(*Payload)(nil),               // 1: opaquetoken.Payload
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_payload_proto_depIdxs = []int32{
	2, // 0: opaquetoken.Payload.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: opaquetoken.Payload.type:type_name -> opaquetoken.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payload_proto_init() }
func file_payload_proto_init() {
	if File_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_proto_rawDesc), len(file_payload_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_proto_goTypes,
		DependencyIndexes: file_payload_proto_depIdxs,
		EnumInfos:         file_payload_proto_enumTypes,
		MessageInfos:      file_payload_proto_msgTypes,
	}.Build()
	File_payload_proto = out.File
	file_payload_proto_goTypes = nil
	file_payload_proto_depIdxs = nil
}
