// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: credentials.proto

package credentials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobProviderCredential struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CredentialType:
	//
	//	*BlobProviderCredential_Gcp
	//	*BlobProviderCredential_Azure
	//	*BlobProviderCredential_S3
	CredentialType isBlobProviderCredential_CredentialType `protobuf_oneof:"credential_type"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlobProviderCredential) Reset() {
	*x = BlobProviderCredential{}
	mi := &file_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobProviderCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobProviderCredential) ProtoMessage() {}

func (x *BlobProviderCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobProviderCredential.ProtoReflect.Descriptor instead.
func (*BlobProviderCredential) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *BlobProviderCredential) GetCredentialType() isBlobProviderCredential_CredentialType {
	if x != nil {
		return x.CredentialType
	}
	return nil
}

func (x *BlobProviderCredential) GetGcp() *GCPCredential {
	if x != nil {
		if x, ok := x.CredentialType.(*BlobProviderCredential_Gcp); ok {
			return x.Gcp
		}
	}
	return nil
}

func (x *BlobProviderCredential) GetAzure() *AzureCredential {
	if x != nil {
		if x, ok := x.CredentialType.(*BlobProviderCredential_Azure); ok {
			return x.Azure
		}
	}
	return nil
}

func (x *BlobProviderCredential) GetS3() *S3Credential {
	if x != nil {
		if x, ok := x.CredentialType.(*BlobProviderCredential_S3); ok {
			return x.S3
		}
	}
	return nil
}

type isBlobProviderCredential_CredentialType interface {
	isBlobProviderCredential_CredentialType()
}

type BlobProviderCredential_Gcp struct {
	Gcp *GCPCredential `protobuf:"bytes,1,opt,name=gcp,proto3,oneof"`
}

type BlobProviderCredential_Azure struct {
	Azure *AzureCredential `protobuf:"bytes,2,opt,name=azure,proto3,oneof"`
}

type BlobProviderCredential_S3 struct {
	S3 *S3Credential `protobuf:"bytes,3,opt,name=s3,proto3,oneof"`
}

func (*BlobProviderCredential_Gcp) isBlobProviderCredential_CredentialType() {}

func (*BlobProviderCredential_Azure) isBlobProviderCredential_CredentialType() {}

func (*BlobProviderCredential_S3) isBlobProviderCredential_CredentialType() {}

type GCPCredential struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	CredentialType string                 `protobuf:"bytes,2,opt,name=credential_type,json=credentialType,proto3" json:"credential_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GCPCredential) Reset() {
	*x = GCPCredential{}
	mi := &file_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GCPCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GCPCredential) ProtoMessage() {}

func (x *GCPCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GCPCredential.ProtoReflect.Descriptor instead.
func (*GCPCredential) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *GCPCredential) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GCPCredential) GetCredentialType() string {
	if x != nil {
		return x.CredentialType
	}
	return ""
}

type AzureCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureCredential) Reset() {
	*x = AzureCredential{}
	mi := &file_credentials_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCredential) ProtoMessage() {}

func (x *AzureCredential) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCredential.ProtoReflect.Descriptor instead.
func (*AzureCredential) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{2}
}

func (x *AzureCredential) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type S3Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S3Credential) Reset() {
	*x = S3Credential{}
	mi := &file_credentials_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Credential) ProtoMessage() {}

func (x *S3Credential) ProtoReflect() protoreflect.Message {
	mi := &file_credentials_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Credential.ProtoReflect.Descriptor instead.
func (*S3Credential) Descriptor() ([]byte, []int) {
	return file_credentials_proto_rawDescGZIP(), []int{3}
}

func (x *S3Credential) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_credentials_proto protoreflect.FileDescriptor

const file_credentials_proto_rawDesc = "" +
	"\n" +
	"\x11credentials.proto\x12\x14pomerium.credentials\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x16BlobProviderCredential\x127\n" +
	"\x03gcp\x18\x01 \x01(\v2#.pomerium.credentials.GCPCredentialH\x00R\x03gcp\x12=\n" +
	"\x05azure\x18\x02 \x01(\v2%.pomerium.credentials.AzureCredentialH\x00R\x05azure\x124\n" +
	"\x02s3\x18\x03 \x01(\v2\".pomerium.credentials.S3CredentialH\x00R\x02s3B\x11\n" +
	"\x0fcredential_type\"L\n" +
	"\rGCPCredential\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12'\n" +
	"\x0fcredential_type\x18\x02 \x01(\tR\x0ecredentialType\"%\n" +
	"\x0fAzureCredential\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\fS3Credential\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB3Z1github.com/pomerium/pomerium/pkg/grpc/credentialsb\x06proto3"

var (
	file_credentials_proto_rawDescOnce sync.Once
	file_credentials_proto_rawDescData []byte
)

func file_credentials_proto_rawDescGZIP() []byte {
	file_credentials_proto_rawDescOnce.Do(func() {
		file_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credentials_proto_rawDesc), len(file_credentials_proto_rawDesc)))
	})
	return file_credentials_proto_rawDescData
}

var file_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_credentials_proto_goTypes = []any{
	(*BlobProviderCredential)(nil), // 0: pomerium.credentials.BlobProviderCredential
	(*GCPCredential)(nil),          // 1: pomerium.credentials.GCPCredential
	(*AzureCredential)(nil),        // 2: pomerium.credentials.AzureCredential
	(*S3Credential)(nil),           // 3: pomerium.credentials.S3Credential
}
var file_credentials_proto_depIdxs = []int32{
	1, // 0: pomerium.credentials.BlobProviderCredential.gcp:type_name -> pomerium.credentials.GCPCredential
	2, // 1: pomerium.credentials.BlobProviderCredential.azure:type_name -> pomerium.credentials.AzureCredential
	3, // 2: pomerium.credentials.BlobProviderCredential.s3:type_name -> pomerium.credentials.S3Credential
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_credentials_proto_init() }
func file_credentials_proto_init() {
	if File_credentials_proto != nil {
		return
	}
	file_credentials_proto_msgTypes[0].OneofWrappers = []any{
		(*BlobProviderCredential_Gcp)(nil),
		(*BlobProviderCredential_Azure)(nil),
		(*BlobProviderCredential_S3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credentials_proto_rawDesc), len(file_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credentials_proto_goTypes,
		DependencyIndexes: file_credentials_proto_depIdxs,
		MessageInfos:      file_credentials_proto_msgTypes,
	}.Build()
	File_credentials_proto = out.File
	file_credentials_proto_goTypes = nil
	file_credentials_proto_depIdxs = nil
}
