// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomerium/pomerium/pkg/identity (interfaces: Authenticator)
//
// Generated by this command:
//
//	mockgen -write_package_comment=false -package oidcprovider -destination authenticator_mock_test.go github.com/pomerium/pomerium/pkg/identity Authenticator
//

package oidcprovider

import (
	context "context"
	http "net/http"
	reflect "reflect"

	identity "github.com/pomerium/pomerium/pkg/identity"
	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticator) Authenticate(arg0 context.Context, arg1 string, arg2 identity.State) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticatorMockRecorder) Authenticate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticator)(nil).Authenticate), arg0, arg1, arg2)
}

// DeviceAccessToken mocks base method.
func (m *MockAuthenticator) DeviceAccessToken(ctx context.Context, r *oauth2.DeviceAuthResponse, state identity.State) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceAccessToken", ctx, r, state)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceAccessToken indicates an expected call of DeviceAccessToken.
func (mr *MockAuthenticatorMockRecorder) DeviceAccessToken(ctx, r, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceAccessToken", reflect.TypeOf((*MockAuthenticator)(nil).DeviceAccessToken), ctx, r, state)
}

// DeviceAuth mocks base method.
func (m *MockAuthenticator) DeviceAuth(ctx context.Context) (*oauth2.DeviceAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceAuth", ctx)
	ret0, _ := ret[0].(*oauth2.DeviceAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceAuth indicates an expected call of DeviceAuth.
func (mr *MockAuthenticatorMockRecorder) DeviceAuth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceAuth", reflect.TypeOf((*MockAuthenticator)(nil).DeviceAuth), ctx)
}

// Name mocks base method.
func (m *MockAuthenticator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAuthenticatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAuthenticator)(nil).Name))
}

// Refresh mocks base method.
func (m *MockAuthenticator) Refresh(arg0 context.Context, arg1 *oauth2.Token, arg2 identity.State) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", arg0, arg1, arg2)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthenticatorMockRecorder) Refresh(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthenticator)(nil).Refresh), arg0, arg1, arg2)
}

// Revoke mocks base method.
func (m *MockAuthenticator) Revoke(arg0 context.Context, arg1 *oauth2.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAuthenticatorMockRecorder) Revoke(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAuthenticator)(nil).Revoke), arg0, arg1)
}

// SignIn mocks base method.
func (m *MockAuthenticator) SignIn(w http.ResponseWriter, r *http.Request, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", w, r, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthenticatorMockRecorder) SignIn(w, r, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthenticator)(nil).SignIn), w, r, state)
}

// SignOut mocks base method.
func (m *MockAuthenticator) SignOut(w http.ResponseWriter, r *http.Request, idTokenHint, authenticateSignedOutURL, redirectToURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", w, r, idTokenHint, authenticateSignedOutURL, redirectToURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignOut indicates an expected call of SignOut.
func (mr *MockAuthenticatorMockRecorder) SignOut(w, r, idTokenHint, authenticateSignedOutURL, redirectToURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockAuthenticator)(nil).SignOut), w, r, idTokenHint, authenticateSignedOutURL, redirectToURL)
}

// UpdateUserInfo mocks base method.
func (m *MockAuthenticator) UpdateUserInfo(ctx context.Context, t *oauth2.Token, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserInfo", ctx, t, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserInfo indicates an expected call of UpdateUserInfo.
func (mr *MockAuthenticatorMockRecorder) UpdateUserInfo(ctx, t, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserInfo", reflect.TypeOf((*MockAuthenticator)(nil).UpdateUserInfo), ctx, t, v)
}

// VerifyAccessToken mocks base method.
func (m *MockAuthenticator) VerifyAccessToken(ctx context.Context, rawAccessToken string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", ctx, rawAccessToken)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockAuthenticatorMockRecorder) VerifyAccessToken(ctx, rawAccessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockAuthenticator)(nil).VerifyAccessToken), ctx, rawAccessToken)
}

// VerifyIdentityToken mocks base method.
func (m *MockAuthenticator) VerifyIdentityToken(ctx context.Context, rawIdentityToken string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIdentityToken", ctx, rawIdentityToken)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIdentityToken indicates an expected call of VerifyIdentityToken.
func (mr *MockAuthenticatorMockRecorder) VerifyIdentityToken(ctx, rawIdentityToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIdentityToken", reflect.TypeOf((*MockAuthenticator)(nil).VerifyIdentityToken), ctx, rawIdentityToken)
}
