// MIT License
//
// Copyright (c) 2020-2025 Charmbracelet, Inc
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// Package table is modified from https://github.com/charmbracelet/bubbles/blob/v2.0.0-beta.1/table/table.go
package table

import (
	"fmt"
	stdslices "slices"
	"strings"

	"charm.land/bubbles/v2/help"
	"charm.land/bubbles/v2/key"
	"charm.land/bubbles/v2/viewport"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/mattn/go-runewidth"

	"github.com/pomerium/pomerium/pkg/slices"
)

// Model defines a state for the table widget.
type Model struct {
	KeyMap KeyMap
	Help   help.Model

	cols   []Column
	rows   []Row
	cursor int
	focus  bool
	styles Styles

	viewport viewport.Model
	start    int
	end      int
}

// Row represents one line in the table.
type Row []string

// Column defines the table structure.
type Column struct {
	Title     string
	Width     int
	CellStyle func(value string) lipgloss.Style
}

// KeyMap defines keybindings. It satisfies to the help.KeyMap interface, which
// is used to render the help menu.
type KeyMap struct {
	LineUp       key.Binding
	LineDown     key.Binding
	PageUp       key.Binding
	PageDown     key.Binding
	HalfPageUp   key.Binding
	HalfPageDown key.Binding
	GotoTop      key.Binding
	GotoBottom   key.Binding
	Deselect     key.Binding
}

// ShortHelp implements the KeyMap interface.
func (km KeyMap) ShortHelp() []key.Binding {
	return []key.Binding{km.LineUp, km.LineDown}
}

// FullHelp implements the KeyMap interface.
func (km KeyMap) FullHelp() [][]key.Binding {
	return [][]key.Binding{
		{km.LineUp, km.LineDown, km.GotoTop, km.GotoBottom},
		{km.PageUp, km.PageDown, km.HalfPageUp, km.HalfPageDown},
	}
}

// DefaultKeyMap returns a default set of keybindings.
func DefaultKeyMap() KeyMap {
	return KeyMap{
		LineUp: key.NewBinding(
			key.WithKeys("up", "k"),
			key.WithHelp("↑/k", "up"),
		),
		LineDown: key.NewBinding(
			key.WithKeys("down", "j"),
			key.WithHelp("↓/j", "down"),
		),
		PageUp: key.NewBinding(
			key.WithKeys("b", "pgup"),
			key.WithHelp("b/pgup", "page up"),
		),
		PageDown: key.NewBinding(
			key.WithKeys("f", "pgdown", "space"),
			key.WithHelp("f/pgdn", "page down"),
		),
		HalfPageUp: key.NewBinding(
			key.WithKeys("u", "ctrl+u"),
			key.WithHelp("u", "½ page up"),
		),
		HalfPageDown: key.NewBinding(
			key.WithKeys("d", "ctrl+d"),
			key.WithHelp("d", "½ page down"),
		),
		GotoTop: key.NewBinding(
			key.WithKeys("home", "g"),
			key.WithHelp("g/home", "go to start"),
		),
		GotoBottom: key.NewBinding(
			key.WithKeys("end", "G"),
			key.WithHelp("G/end", "go to end"),
		),
		Deselect: key.NewBinding(
			key.WithKeys("esc"),
			key.WithHelp("esc", "deselect row"),
		),
	}
}

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	Header           lipgloss.Style
	Cell             lipgloss.Style
	Selected         lipgloss.Style
	Border           lipgloss.Border
	Focused          lipgloss.Style
	BorderTitleLeft  string
	BorderTitleRight string
}

func (m *Model) defaultViewportStyle() lipgloss.Style {
	return lipgloss.NewStyle().Border(m.styles.Border, false, true, true, true)
}

// Option is used to set options in New. For example:
//
//	table := New(WithColumns([]Column{{Title: "ID", Width: 10}}))
type Option func(*Model)

// New creates a new model for the table widget.
func New(styles Styles, opts ...Option) Model {
	styles.Header = styles.Header.Border(styles.Border, true, true, false, true)

	m := Model{
		styles:   styles,
		cursor:   -1,
		viewport: viewport.New(viewport.WithHeight(20)),

		KeyMap: DefaultKeyMap(),
		Help:   help.New(),
	}
	m.viewport.Style = m.defaultViewportStyle()

	for _, opt := range opts {
		opt(&m)
	}

	m.UpdateViewport()

	return m
}

// WithColumns sets the table columns (headers).
func WithColumns(cols []Column) Option {
	return func(m *Model) {
		m.cols = cols
	}
}

// WithRows sets the table rows (data).
func WithRows(rows []Row) Option {
	return func(m *Model) {
		m.rows = rows
	}
}

// WithHeight sets the height of the table.
func WithHeight(h int) Option {
	return func(m *Model) {
		m.viewport.SetHeight(h - lipgloss.Height(m.headersView()))
	}
}

// WithWidth sets the width of the table.
func WithWidth(w int) Option {
	return func(m *Model) {
		m.viewport.SetWidth(w)
	}
}

// WithKeyMap sets the key map.
func WithKeyMap(km KeyMap) Option {
	return func(m *Model) {
		m.KeyMap = km
	}
}

// Update is the Bubble Tea update loop.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	if !m.focus {
		return m, nil
	}

	switch msg := msg.(type) {
	case tea.KeyPressMsg:
		switch {
		case key.Matches(msg, m.KeyMap.LineUp):
			m.MoveUp(1)
		case key.Matches(msg, m.KeyMap.LineDown):
			m.MoveDown(1)
		case key.Matches(msg, m.KeyMap.PageUp):
			m.MoveUp(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.PageDown):
			m.MoveDown(m.viewport.Height())
		case key.Matches(msg, m.KeyMap.HalfPageUp):
			m.MoveUp(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.HalfPageDown):
			m.MoveDown(m.viewport.Height() / 2) //nolint:mnd
		case key.Matches(msg, m.KeyMap.GotoTop):
			m.GotoTop()
		case key.Matches(msg, m.KeyMap.GotoBottom):
			m.GotoBottom()
		case key.Matches(msg, m.KeyMap.Deselect):
			m.cursor = -1
			m.UpdateViewport()
		}
	case tea.MouseClickMsg:
		switch msg.Button {
		case tea.MouseLeft:
			if msg.X >= m.styles.Border.GetLeftSize() &&
				msg.X <= m.Width()-m.styles.Border.GetRightSize()-1 &&
				msg.Y >= m.styles.Border.GetTopSize()+1 { // +1 for the header
				// find out what row was clicked on
				if row := m.start + (msg.Y - 2); row < m.end {
					m.SetCursor(row)
				} else {
					m.cursor = -1
					m.UpdateViewport()
				}
			}
		}
	}

	return m, nil
}

// Focused returns the focus state of the table.
func (m Model) Focused() bool {
	return m.focus
}

// Focus focuses the table, allowing the user to move around the rows and
// interact.
func (m *Model) Focus() {
	m.focus = true
	m.viewport.Style = m.defaultViewportStyle().Inherit(m.styles.Focused)
	m.UpdateViewport()
}

// Blur blurs the table, preventing selection or movement.
func (m *Model) Blur() {
	m.focus = false
	m.viewport.Style = m.defaultViewportStyle()
	m.UpdateViewport()
}

// View renders the component.
func (m Model) View() string {
	return m.headersView() + "\n" + m.viewport.View()
}

// HelpView is a helper method for rendering the help menu from the keymap.
// Note that this view is not rendered by default and you must call it
// manually in your application, where applicable.
func (m Model) HelpView() string {
	return m.Help.View(m.KeyMap)
}

// UpdateViewport updates the list content based on the previously defined
// columns and rows.
func (m *Model) UpdateViewport() {
	renderedRows := make([]string, 0, len(m.rows))

	// Render only rows from: m.cursor-m.viewport.Height to: m.cursor+m.viewport.Height
	// Constant runtime, independent of number of rows in a table.
	// Limits the number of renderedRows to a maximum of 2*m.viewport.Height
	if m.cursor >= 0 {
		m.start = clamp(m.cursor-m.viewport.Height(), 0, m.cursor)
	} else {
		m.start = 0
	}
	m.end = clamp(m.cursor+m.viewport.Height(), m.cursor, len(m.rows))
	for i := m.start; i < m.end; i++ {
		renderedRows = append(renderedRows, m.renderRow(i))
	}

	m.viewport.SetContent(
		lipgloss.JoinVertical(lipgloss.Left, renderedRows...),
	)
}

// SelectedRow returns the selected row.
// You can cast it to your own implementation.
func (m Model) SelectedRow() Row {
	if m.cursor < 0 || m.cursor >= len(m.rows) {
		return nil
	}

	return m.rows[m.cursor]
}

// Rows returns the current rows.
func (m Model) Rows() []Row {
	return m.rows
}

// Columns returns the current columns.
func (m Model) Columns() []Column {
	return m.cols
}

// SetRows sets a new rows state.
func (m *Model) SetRows(r []Row) {
	m.rows = r

	if m.cursor > 0 && m.cursor > len(m.rows)-1 {
		m.cursor = len(m.rows) - 1
	}

	m.UpdateViewport()
}

// SetColumns sets a new columns state.
func (m *Model) SetColumns(c []Column) {
	m.cols = c
	m.UpdateViewport()
}

// SetWidth sets the width of the viewport of the table.
func (m *Model) SetWidth(w int) {
	m.viewport.SetWidth(w)
	m.UpdateViewport()
}

// SetHeight sets the height of the viewport of the table.
func (m *Model) SetHeight(h int) {
	m.viewport.SetHeight(h - 2) // header height should always be 1 + top border
	m.UpdateViewport()
}

func (m *Model) SetSize(w, h int) {
	m.viewport.SetWidth(w)
	m.viewport.SetHeight(h - 2) // header height should always be 1 + top border
	m.UpdateViewport()
}

func (m *Model) SetSizeAndColumns(w, h int, c []Column) {
	m.viewport.SetWidth(w)
	m.viewport.SetHeight(h - 2) // header height should always be 1 + top border
	m.cols = c
	m.UpdateViewport()
}

// Height returns the viewport height of the table.
func (m Model) Height() int {
	return m.viewport.Height()
}

// Width returns the viewport width of the table.
func (m Model) Width() int {
	return m.viewport.Width()
}

// Cursor returns the index of the selected row.
func (m Model) Cursor() int {
	return m.cursor
}

// SetCursor sets the cursor position in the table.
func (m *Model) SetCursor(n int) {
	m.cursor = clamp(n, 0, len(m.rows)-1)
	m.UpdateViewport()
}

// MoveUp moves the selection up by any number of rows.
// It can not go above the first row.
func (m *Model) MoveUp(n int) {
	m.cursor = clamp(m.cursor-n, 0, len(m.rows)-1)

	offset := m.viewport.YOffset()
	switch {
	case m.start == 0:
		offset = clamp(offset, 0, m.cursor)
	case m.start < m.viewport.Height():
		offset = clamp(clamp(offset+n, 0, m.cursor), 0, m.viewport.Height())
	case offset >= 1:
		offset = clamp(offset+n, 1, m.viewport.Height())
	}
	m.viewport.SetYOffset(offset)
	m.UpdateViewport()
}

// MoveDown moves the selection down by any number of rows.
// It can not go below the last row.
func (m *Model) MoveDown(n int) {
	m.cursor = clamp(m.cursor+n, 0, len(m.rows)-1)
	m.UpdateViewport()

	offset := m.viewport.YOffset()
	switch {
	case m.end == len(m.rows) && offset > 0:
		offset = clamp(offset-n, 1, m.viewport.Height())
	case m.cursor > (m.end-m.start)/2 && offset > 0:
		offset = clamp(offset-n, 1, m.cursor)
	case offset > 1:
	case m.cursor > offset+m.viewport.Height()-1:
		offset = clamp(offset+1, 0, 1)
	}
	m.viewport.SetYOffset(offset)
}

// GotoTop moves the selection to the first row.
func (m *Model) GotoTop() {
	m.MoveUp(m.cursor)
}

// GotoBottom moves the selection to the last row.
func (m *Model) GotoBottom() {
	m.MoveDown(len(m.rows))
}

// FromValues create the table rows from a simple string. It uses `\n` by
// default for getting all the rows and the given separator for the fields on
// each row.
func (m *Model) FromValues(value, separator string) {
	rows := []Row{}
	for _, line := range strings.Split(value, "\n") {
		r := Row{}
		for _, field := range strings.Split(line, separator) {
			r = append(r, field)
		}
		rows = append(rows, r)
	}

	m.SetRows(rows)
}

func (m Model) headersView() string {
	s := make([]string, 0, len(m.cols))
	style := m.styles.Header
	if m.focus {
		style = style.Inherit(m.styles.Focused)
	}
	for c, col := range m.cols {
		if col.Width <= 0 {
			continue
		}
		style := style
		if len(m.cols) > 1 {
			if c == 0 {
				style = style.UnsetBorderRight()
			} else if c > 0 && c < len(m.cols)-1 {
				style = style.UnsetBorderLeft().UnsetBorderRight()
			} else if c == len(m.cols)-1 {
				style = style.UnsetBorderLeft()
			}
		}
		style = style.
			Width(col.Width).
			MaxWidth(col.Width)
		renderedCell := style.UnsetBorderTop().Render(runewidth.Truncate(col.Title, col.Width-style.GetHorizontalFrameSize(), "…"))
		s = append(s, renderedCell)
	}

	header := lipgloss.JoinHorizontal(lipgloss.Top, s...)
	headerTopBorder := style.Width(lipgloss.Width(header)).Render()
	headerTopBorder = headerTopBorder[:strings.IndexRune(headerTopBorder, '\n')]
	if m.styles.Border.Top != "" &&
		(m.styles.BorderTitleLeft != "" || m.styles.BorderTitleRight != "") {
		topRune := []rune(m.styles.Border.Top)[0]
		borderRunes := []rune(headerTopBorder)
		left := stdslices.Index(borderRunes, topRune)
		right := slices.LastIndex(borderRunes, topRune)
		if m.styles.BorderTitleLeft != "" {
			text := []rune(fmt.Sprintf("╴%s╶", m.styles.BorderTitleLeft))
			if left+len(text) < right {
				left += copy(borderRunes[left:], text)
			}
		}
		if m.styles.BorderTitleRight != "" {
			text := []rune(fmt.Sprintf("╴%s╶", m.styles.BorderTitleRight))
			if right-len(text) > left {
				copy(borderRunes[right-len(text)+1:], text)
			}
		}
		headerTopBorder = string(borderRunes)
	}
	return lipgloss.JoinVertical(lipgloss.Left, headerTopBorder, header)
}

func (m *Model) renderRow(r int) string {
	s := make([]string, 0, len(m.cols))
	for c, value := range m.rows[r] {
		if m.cols[c].Width <= 0 {
			continue
		}
		cellWidth := m.cols[c].Width
		if len(m.cols) > 1 && (c == 0 || c == len(m.cols)-1) {
			cellWidth--
		}
		style := m.styles.Cell.Width(cellWidth).MaxWidth(cellWidth)
		if m.cols[c].CellStyle != nil {
			style = style.Inherit(m.cols[c].CellStyle(value))
		}

		if r == m.cursor && m.focus {
			style = style.Inherit(m.styles.Selected)
		}
		renderedCell := style.Render(runewidth.Truncate(value, cellWidth-style.GetHorizontalPadding(), "…"))
		s = append(s, renderedCell)
	}

	row := lipgloss.JoinHorizontal(lipgloss.Top, s...)

	return row
}

func clamp(v, low, high int) int {
	return min(max(v, low), high)
}
