// Code generated by internal/generate DO NOT EDIT.
package config

import (
	"errors"
	config "github.com/pomerium/pomerium/pkg/grpc/config"
)

type BlobStorageSettings struct {
	BucketURI     *string `mapstructure:"bucket_uri" yaml:"bucket_uri,omitzero"`
	ManagedPrefix *string `mapstructure:"managed_prefix" yaml:"managed_prefix,omitzero"`
}

type Route struct {
	AllowUpgrades *[]string `mapstructure:"allow_upgrades" yaml:"allow_upgrades,omitzero"`
}

type Settings struct {
	AllowUpgrades       *[]string `mapstructure:"allow_upgrades" yaml:"allow_upgrades,omitzero"`
	AutoApplyChangesets *bool     `mapstructure:"auto_apply_changesets" yaml:"auto_apply_changesets,omitzero"`
}

func convertBlobStorageSettingsFromProto(dst *BlobStorageSettings, src *config.BlobStorageSettings) error {
	if src == nil {
		return nil
	}
	return errors.Join(
		convertOptionalStringFromProto(&dst.BucketURI, src.BucketUri),
		convertOptionalStringFromProto(&dst.ManagedPrefix, src.ManagedPrefix),
	)
}

func convertOptionalBlobStorageSettingsFromProto(dst **BlobStorageSettings, src *config.BlobStorageSettings) error {
	if src == nil {
		return nil
	}
	*dst = new(BlobStorageSettings)
	return errors.Join(
		convertOptionalStringFromProto(&(*dst).BucketURI, src.BucketUri),
		convertOptionalStringFromProto(&(*dst).ManagedPrefix, src.ManagedPrefix),
	)
}

func convertRouteFromProto(dst *Route, src *config.Route) error {
	if src == nil {
		return nil
	}
	return errors.Join(
		convertOptionalRouteStringListFromProto(&dst.AllowUpgrades, src.AllowUpgrades),
	)
}

func convertOptionalRouteFromProto(dst **Route, src *config.Route) error {
	if src == nil {
		return nil
	}
	*dst = new(Route)
	return errors.Join(
		convertOptionalRouteStringListFromProto(&(*dst).AllowUpgrades, src.AllowUpgrades),
	)
}

func convertSettingsFromProto(dst *Settings, src *config.Settings) error {
	if src == nil {
		return nil
	}
	return errors.Join(
		convertOptionalSettingsStringListFromProto(&dst.AllowUpgrades, src.AllowUpgrades),
		convertOptionalBooleanFromProto(&dst.AutoApplyChangesets, src.AutoApplyChangesets),
	)
}

func convertOptionalSettingsFromProto(dst **Settings, src *config.Settings) error {
	if src == nil {
		return nil
	}
	*dst = new(Settings)
	return errors.Join(
		convertOptionalSettingsStringListFromProto(&(*dst).AllowUpgrades, src.AllowUpgrades),
		convertOptionalBooleanFromProto(&(*dst).AutoApplyChangesets, src.AutoApplyChangesets),
	)
}

func convertBlobStorageSettingsToProto(dst *config.BlobStorageSettings, src *BlobStorageSettings) error {
	if src == nil {
		return nil
	}
	return errors.Join(
		convertOptionalStringToProto(&dst.BucketUri, src.BucketURI),
		convertOptionalStringToProto(&dst.ManagedPrefix, src.ManagedPrefix),
	)
}

func convertOptionalBlobStorageSettingsToProto(dst **config.BlobStorageSettings, src *BlobStorageSettings) error {
	if src == nil {
		return nil
	}
	*dst = new(config.BlobStorageSettings)
	return errors.Join(
		convertOptionalStringToProto(&(*dst).BucketUri, src.BucketURI),
		convertOptionalStringToProto(&(*dst).ManagedPrefix, src.ManagedPrefix),
	)
}

func convertRouteToProto(dst *config.Route, src *Route) error {
	if src == nil {
		return nil
	}
	return errors.Join(
		convertOptionalRouteStringListToProto(&dst.AllowUpgrades, src.AllowUpgrades),
	)
}

func convertOptionalRouteToProto(dst **config.Route, src *Route) error {
	if src == nil {
		return nil
	}
	*dst = new(config.Route)
	return errors.Join(
		convertOptionalRouteStringListToProto(&(*dst).AllowUpgrades, src.AllowUpgrades),
	)
}

func convertSettingsToProto(dst *config.Settings, src *Settings) error {
	if src == nil {
		return nil
	}
	return errors.Join(
		convertOptionalSettingsStringListToProto(&dst.AllowUpgrades, src.AllowUpgrades),
		convertOptionalBooleanToProto(&dst.AutoApplyChangesets, src.AutoApplyChangesets),
	)
}

func convertOptionalSettingsToProto(dst **config.Settings, src *Settings) error {
	if src == nil {
		return nil
	}
	*dst = new(config.Settings)
	return errors.Join(
		convertOptionalSettingsStringListToProto(&(*dst).AllowUpgrades, src.AllowUpgrades),
		convertOptionalBooleanToProto(&(*dst).AutoApplyChangesets, src.AutoApplyChangesets),
	)
}
