// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: databroker.proto

package databrokerconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	databroker "github.com/pomerium/pomerium/pkg/grpc/databroker"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DataBrokerServiceName is the fully-qualified name of the DataBrokerService service.
	DataBrokerServiceName = "databroker.DataBrokerService"
	// CheckpointServiceName is the fully-qualified name of the CheckpointService service.
	CheckpointServiceName = "databroker.CheckpointService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DataBrokerServiceAcquireLeaseProcedure is the fully-qualified name of the DataBrokerService's
	// AcquireLease RPC.
	DataBrokerServiceAcquireLeaseProcedure = "/databroker.DataBrokerService/AcquireLease"
	// DataBrokerServiceClearProcedure is the fully-qualified name of the DataBrokerService's Clear RPC.
	DataBrokerServiceClearProcedure = "/databroker.DataBrokerService/Clear"
	// DataBrokerServiceGetProcedure is the fully-qualified name of the DataBrokerService's Get RPC.
	DataBrokerServiceGetProcedure = "/databroker.DataBrokerService/Get"
	// DataBrokerServiceListTypesProcedure is the fully-qualified name of the DataBrokerService's
	// ListTypes RPC.
	DataBrokerServiceListTypesProcedure = "/databroker.DataBrokerService/ListTypes"
	// DataBrokerServicePutProcedure is the fully-qualified name of the DataBrokerService's Put RPC.
	DataBrokerServicePutProcedure = "/databroker.DataBrokerService/Put"
	// DataBrokerServicePatchProcedure is the fully-qualified name of the DataBrokerService's Patch RPC.
	DataBrokerServicePatchProcedure = "/databroker.DataBrokerService/Patch"
	// DataBrokerServiceQueryProcedure is the fully-qualified name of the DataBrokerService's Query RPC.
	DataBrokerServiceQueryProcedure = "/databroker.DataBrokerService/Query"
	// DataBrokerServiceReleaseLeaseProcedure is the fully-qualified name of the DataBrokerService's
	// ReleaseLease RPC.
	DataBrokerServiceReleaseLeaseProcedure = "/databroker.DataBrokerService/ReleaseLease"
	// DataBrokerServiceRenewLeaseProcedure is the fully-qualified name of the DataBrokerService's
	// RenewLease RPC.
	DataBrokerServiceRenewLeaseProcedure = "/databroker.DataBrokerService/RenewLease"
	// DataBrokerServiceServerInfoProcedure is the fully-qualified name of the DataBrokerService's
	// ServerInfo RPC.
	DataBrokerServiceServerInfoProcedure = "/databroker.DataBrokerService/ServerInfo"
	// DataBrokerServiceSetOptionsProcedure is the fully-qualified name of the DataBrokerService's
	// SetOptions RPC.
	DataBrokerServiceSetOptionsProcedure = "/databroker.DataBrokerService/SetOptions"
	// DataBrokerServiceSyncProcedure is the fully-qualified name of the DataBrokerService's Sync RPC.
	DataBrokerServiceSyncProcedure = "/databroker.DataBrokerService/Sync"
	// DataBrokerServiceSyncLatestProcedure is the fully-qualified name of the DataBrokerService's
	// SyncLatest RPC.
	DataBrokerServiceSyncLatestProcedure = "/databroker.DataBrokerService/SyncLatest"
	// CheckpointServiceGetCheckpointProcedure is the fully-qualified name of the CheckpointService's
	// GetCheckpoint RPC.
	CheckpointServiceGetCheckpointProcedure = "/databroker.CheckpointService/GetCheckpoint"
	// CheckpointServiceSetCheckpointProcedure is the fully-qualified name of the CheckpointService's
	// SetCheckpoint RPC.
	CheckpointServiceSetCheckpointProcedure = "/databroker.CheckpointService/SetCheckpoint"
)

// DataBrokerServiceClient is a client for the databroker.DataBrokerService service.
type DataBrokerServiceClient interface {
	// AcquireLease acquires a distributed mutex lease.
	AcquireLease(context.Context, *connect.Request[databroker.AcquireLeaseRequest]) (*connect.Response[databroker.AcquireLeaseResponse], error)
	// Clear removes all records from the databroker.
	Clear(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ClearResponse], error)
	// Get gets a record.
	Get(context.Context, *connect.Request[databroker.GetRequest]) (*connect.Response[databroker.GetResponse], error)
	// ListTypes lists all the known record types.
	ListTypes(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ListTypesResponse], error)
	// Put saves a record.
	Put(context.Context, *connect.Request[databroker.PutRequest]) (*connect.Response[databroker.PutResponse], error)
	// Patch updates specific fields of an existing record.
	Patch(context.Context, *connect.Request[databroker.PatchRequest]) (*connect.Response[databroker.PatchResponse], error)
	// Query queries for records.
	Query(context.Context, *connect.Request[databroker.QueryRequest]) (*connect.Response[databroker.QueryResponse], error)
	// ReleaseLease releases a distributed mutex lease.
	ReleaseLease(context.Context, *connect.Request[databroker.ReleaseLeaseRequest]) (*connect.Response[emptypb.Empty], error)
	// RenewLease renews a distributed mutex lease.
	RenewLease(context.Context, *connect.Request[databroker.RenewLeaseRequest]) (*connect.Response[emptypb.Empty], error)
	// ServerInfo returns information about the databroker server.
	ServerInfo(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ServerInfoResponse], error)
	// SetOptions sets the options for a type in the databroker.
	SetOptions(context.Context, *connect.Request[databroker.SetOptionsRequest]) (*connect.Response[databroker.SetOptionsResponse], error)
	// Sync streams changes to records after the specified version.
	Sync(context.Context, *connect.Request[databroker.SyncRequest]) (*connect.ServerStreamForClient[databroker.SyncResponse], error)
	// SyncLatest streams the latest version of every record.
	SyncLatest(context.Context, *connect.Request[databroker.SyncLatestRequest]) (*connect.ServerStreamForClient[databroker.SyncLatestResponse], error)
}

// NewDataBrokerServiceClient constructs a client for the databroker.DataBrokerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDataBrokerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DataBrokerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dataBrokerServiceMethods := databroker.File_databroker_proto.Services().ByName("DataBrokerService").Methods()
	return &dataBrokerServiceClient{
		acquireLease: connect.NewClient[databroker.AcquireLeaseRequest, databroker.AcquireLeaseResponse](
			httpClient,
			baseURL+DataBrokerServiceAcquireLeaseProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("AcquireLease")),
			connect.WithClientOptions(opts...),
		),
		clear: connect.NewClient[emptypb.Empty, databroker.ClearResponse](
			httpClient,
			baseURL+DataBrokerServiceClearProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("Clear")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[databroker.GetRequest, databroker.GetResponse](
			httpClient,
			baseURL+DataBrokerServiceGetProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		listTypes: connect.NewClient[emptypb.Empty, databroker.ListTypesResponse](
			httpClient,
			baseURL+DataBrokerServiceListTypesProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("ListTypes")),
			connect.WithClientOptions(opts...),
		),
		put: connect.NewClient[databroker.PutRequest, databroker.PutResponse](
			httpClient,
			baseURL+DataBrokerServicePutProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("Put")),
			connect.WithClientOptions(opts...),
		),
		patch: connect.NewClient[databroker.PatchRequest, databroker.PatchResponse](
			httpClient,
			baseURL+DataBrokerServicePatchProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("Patch")),
			connect.WithClientOptions(opts...),
		),
		query: connect.NewClient[databroker.QueryRequest, databroker.QueryResponse](
			httpClient,
			baseURL+DataBrokerServiceQueryProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("Query")),
			connect.WithClientOptions(opts...),
		),
		releaseLease: connect.NewClient[databroker.ReleaseLeaseRequest, emptypb.Empty](
			httpClient,
			baseURL+DataBrokerServiceReleaseLeaseProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("ReleaseLease")),
			connect.WithClientOptions(opts...),
		),
		renewLease: connect.NewClient[databroker.RenewLeaseRequest, emptypb.Empty](
			httpClient,
			baseURL+DataBrokerServiceRenewLeaseProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("RenewLease")),
			connect.WithClientOptions(opts...),
		),
		serverInfo: connect.NewClient[emptypb.Empty, databroker.ServerInfoResponse](
			httpClient,
			baseURL+DataBrokerServiceServerInfoProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("ServerInfo")),
			connect.WithClientOptions(opts...),
		),
		setOptions: connect.NewClient[databroker.SetOptionsRequest, databroker.SetOptionsResponse](
			httpClient,
			baseURL+DataBrokerServiceSetOptionsProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("SetOptions")),
			connect.WithClientOptions(opts...),
		),
		sync: connect.NewClient[databroker.SyncRequest, databroker.SyncResponse](
			httpClient,
			baseURL+DataBrokerServiceSyncProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
		syncLatest: connect.NewClient[databroker.SyncLatestRequest, databroker.SyncLatestResponse](
			httpClient,
			baseURL+DataBrokerServiceSyncLatestProcedure,
			connect.WithSchema(dataBrokerServiceMethods.ByName("SyncLatest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dataBrokerServiceClient implements DataBrokerServiceClient.
type dataBrokerServiceClient struct {
	acquireLease *connect.Client[databroker.AcquireLeaseRequest, databroker.AcquireLeaseResponse]
	clear        *connect.Client[emptypb.Empty, databroker.ClearResponse]
	get          *connect.Client[databroker.GetRequest, databroker.GetResponse]
	listTypes    *connect.Client[emptypb.Empty, databroker.ListTypesResponse]
	put          *connect.Client[databroker.PutRequest, databroker.PutResponse]
	patch        *connect.Client[databroker.PatchRequest, databroker.PatchResponse]
	query        *connect.Client[databroker.QueryRequest, databroker.QueryResponse]
	releaseLease *connect.Client[databroker.ReleaseLeaseRequest, emptypb.Empty]
	renewLease   *connect.Client[databroker.RenewLeaseRequest, emptypb.Empty]
	serverInfo   *connect.Client[emptypb.Empty, databroker.ServerInfoResponse]
	setOptions   *connect.Client[databroker.SetOptionsRequest, databroker.SetOptionsResponse]
	sync         *connect.Client[databroker.SyncRequest, databroker.SyncResponse]
	syncLatest   *connect.Client[databroker.SyncLatestRequest, databroker.SyncLatestResponse]
}

// AcquireLease calls databroker.DataBrokerService.AcquireLease.
func (c *dataBrokerServiceClient) AcquireLease(ctx context.Context, req *connect.Request[databroker.AcquireLeaseRequest]) (*connect.Response[databroker.AcquireLeaseResponse], error) {
	return c.acquireLease.CallUnary(ctx, req)
}

// Clear calls databroker.DataBrokerService.Clear.
func (c *dataBrokerServiceClient) Clear(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ClearResponse], error) {
	return c.clear.CallUnary(ctx, req)
}

// Get calls databroker.DataBrokerService.Get.
func (c *dataBrokerServiceClient) Get(ctx context.Context, req *connect.Request[databroker.GetRequest]) (*connect.Response[databroker.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// ListTypes calls databroker.DataBrokerService.ListTypes.
func (c *dataBrokerServiceClient) ListTypes(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ListTypesResponse], error) {
	return c.listTypes.CallUnary(ctx, req)
}

// Put calls databroker.DataBrokerService.Put.
func (c *dataBrokerServiceClient) Put(ctx context.Context, req *connect.Request[databroker.PutRequest]) (*connect.Response[databroker.PutResponse], error) {
	return c.put.CallUnary(ctx, req)
}

// Patch calls databroker.DataBrokerService.Patch.
func (c *dataBrokerServiceClient) Patch(ctx context.Context, req *connect.Request[databroker.PatchRequest]) (*connect.Response[databroker.PatchResponse], error) {
	return c.patch.CallUnary(ctx, req)
}

// Query calls databroker.DataBrokerService.Query.
func (c *dataBrokerServiceClient) Query(ctx context.Context, req *connect.Request[databroker.QueryRequest]) (*connect.Response[databroker.QueryResponse], error) {
	return c.query.CallUnary(ctx, req)
}

// ReleaseLease calls databroker.DataBrokerService.ReleaseLease.
func (c *dataBrokerServiceClient) ReleaseLease(ctx context.Context, req *connect.Request[databroker.ReleaseLeaseRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.releaseLease.CallUnary(ctx, req)
}

// RenewLease calls databroker.DataBrokerService.RenewLease.
func (c *dataBrokerServiceClient) RenewLease(ctx context.Context, req *connect.Request[databroker.RenewLeaseRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.renewLease.CallUnary(ctx, req)
}

// ServerInfo calls databroker.DataBrokerService.ServerInfo.
func (c *dataBrokerServiceClient) ServerInfo(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ServerInfoResponse], error) {
	return c.serverInfo.CallUnary(ctx, req)
}

// SetOptions calls databroker.DataBrokerService.SetOptions.
func (c *dataBrokerServiceClient) SetOptions(ctx context.Context, req *connect.Request[databroker.SetOptionsRequest]) (*connect.Response[databroker.SetOptionsResponse], error) {
	return c.setOptions.CallUnary(ctx, req)
}

// Sync calls databroker.DataBrokerService.Sync.
func (c *dataBrokerServiceClient) Sync(ctx context.Context, req *connect.Request[databroker.SyncRequest]) (*connect.ServerStreamForClient[databroker.SyncResponse], error) {
	return c.sync.CallServerStream(ctx, req)
}

// SyncLatest calls databroker.DataBrokerService.SyncLatest.
func (c *dataBrokerServiceClient) SyncLatest(ctx context.Context, req *connect.Request[databroker.SyncLatestRequest]) (*connect.ServerStreamForClient[databroker.SyncLatestResponse], error) {
	return c.syncLatest.CallServerStream(ctx, req)
}

// DataBrokerServiceHandler is an implementation of the databroker.DataBrokerService service.
type DataBrokerServiceHandler interface {
	// AcquireLease acquires a distributed mutex lease.
	AcquireLease(context.Context, *connect.Request[databroker.AcquireLeaseRequest]) (*connect.Response[databroker.AcquireLeaseResponse], error)
	// Clear removes all records from the databroker.
	Clear(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ClearResponse], error)
	// Get gets a record.
	Get(context.Context, *connect.Request[databroker.GetRequest]) (*connect.Response[databroker.GetResponse], error)
	// ListTypes lists all the known record types.
	ListTypes(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ListTypesResponse], error)
	// Put saves a record.
	Put(context.Context, *connect.Request[databroker.PutRequest]) (*connect.Response[databroker.PutResponse], error)
	// Patch updates specific fields of an existing record.
	Patch(context.Context, *connect.Request[databroker.PatchRequest]) (*connect.Response[databroker.PatchResponse], error)
	// Query queries for records.
	Query(context.Context, *connect.Request[databroker.QueryRequest]) (*connect.Response[databroker.QueryResponse], error)
	// ReleaseLease releases a distributed mutex lease.
	ReleaseLease(context.Context, *connect.Request[databroker.ReleaseLeaseRequest]) (*connect.Response[emptypb.Empty], error)
	// RenewLease renews a distributed mutex lease.
	RenewLease(context.Context, *connect.Request[databroker.RenewLeaseRequest]) (*connect.Response[emptypb.Empty], error)
	// ServerInfo returns information about the databroker server.
	ServerInfo(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ServerInfoResponse], error)
	// SetOptions sets the options for a type in the databroker.
	SetOptions(context.Context, *connect.Request[databroker.SetOptionsRequest]) (*connect.Response[databroker.SetOptionsResponse], error)
	// Sync streams changes to records after the specified version.
	Sync(context.Context, *connect.Request[databroker.SyncRequest], *connect.ServerStream[databroker.SyncResponse]) error
	// SyncLatest streams the latest version of every record.
	SyncLatest(context.Context, *connect.Request[databroker.SyncLatestRequest], *connect.ServerStream[databroker.SyncLatestResponse]) error
}

// NewDataBrokerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDataBrokerServiceHandler(svc DataBrokerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dataBrokerServiceMethods := databroker.File_databroker_proto.Services().ByName("DataBrokerService").Methods()
	dataBrokerServiceAcquireLeaseHandler := connect.NewUnaryHandler(
		DataBrokerServiceAcquireLeaseProcedure,
		svc.AcquireLease,
		connect.WithSchema(dataBrokerServiceMethods.ByName("AcquireLease")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceClearHandler := connect.NewUnaryHandler(
		DataBrokerServiceClearProcedure,
		svc.Clear,
		connect.WithSchema(dataBrokerServiceMethods.ByName("Clear")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceGetHandler := connect.NewUnaryHandler(
		DataBrokerServiceGetProcedure,
		svc.Get,
		connect.WithSchema(dataBrokerServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceListTypesHandler := connect.NewUnaryHandler(
		DataBrokerServiceListTypesProcedure,
		svc.ListTypes,
		connect.WithSchema(dataBrokerServiceMethods.ByName("ListTypes")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServicePutHandler := connect.NewUnaryHandler(
		DataBrokerServicePutProcedure,
		svc.Put,
		connect.WithSchema(dataBrokerServiceMethods.ByName("Put")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServicePatchHandler := connect.NewUnaryHandler(
		DataBrokerServicePatchProcedure,
		svc.Patch,
		connect.WithSchema(dataBrokerServiceMethods.ByName("Patch")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceQueryHandler := connect.NewUnaryHandler(
		DataBrokerServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(dataBrokerServiceMethods.ByName("Query")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceReleaseLeaseHandler := connect.NewUnaryHandler(
		DataBrokerServiceReleaseLeaseProcedure,
		svc.ReleaseLease,
		connect.WithSchema(dataBrokerServiceMethods.ByName("ReleaseLease")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceRenewLeaseHandler := connect.NewUnaryHandler(
		DataBrokerServiceRenewLeaseProcedure,
		svc.RenewLease,
		connect.WithSchema(dataBrokerServiceMethods.ByName("RenewLease")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceServerInfoHandler := connect.NewUnaryHandler(
		DataBrokerServiceServerInfoProcedure,
		svc.ServerInfo,
		connect.WithSchema(dataBrokerServiceMethods.ByName("ServerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceSetOptionsHandler := connect.NewUnaryHandler(
		DataBrokerServiceSetOptionsProcedure,
		svc.SetOptions,
		connect.WithSchema(dataBrokerServiceMethods.ByName("SetOptions")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceSyncHandler := connect.NewServerStreamHandler(
		DataBrokerServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(dataBrokerServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	dataBrokerServiceSyncLatestHandler := connect.NewServerStreamHandler(
		DataBrokerServiceSyncLatestProcedure,
		svc.SyncLatest,
		connect.WithSchema(dataBrokerServiceMethods.ByName("SyncLatest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/databroker.DataBrokerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DataBrokerServiceAcquireLeaseProcedure:
			dataBrokerServiceAcquireLeaseHandler.ServeHTTP(w, r)
		case DataBrokerServiceClearProcedure:
			dataBrokerServiceClearHandler.ServeHTTP(w, r)
		case DataBrokerServiceGetProcedure:
			dataBrokerServiceGetHandler.ServeHTTP(w, r)
		case DataBrokerServiceListTypesProcedure:
			dataBrokerServiceListTypesHandler.ServeHTTP(w, r)
		case DataBrokerServicePutProcedure:
			dataBrokerServicePutHandler.ServeHTTP(w, r)
		case DataBrokerServicePatchProcedure:
			dataBrokerServicePatchHandler.ServeHTTP(w, r)
		case DataBrokerServiceQueryProcedure:
			dataBrokerServiceQueryHandler.ServeHTTP(w, r)
		case DataBrokerServiceReleaseLeaseProcedure:
			dataBrokerServiceReleaseLeaseHandler.ServeHTTP(w, r)
		case DataBrokerServiceRenewLeaseProcedure:
			dataBrokerServiceRenewLeaseHandler.ServeHTTP(w, r)
		case DataBrokerServiceServerInfoProcedure:
			dataBrokerServiceServerInfoHandler.ServeHTTP(w, r)
		case DataBrokerServiceSetOptionsProcedure:
			dataBrokerServiceSetOptionsHandler.ServeHTTP(w, r)
		case DataBrokerServiceSyncProcedure:
			dataBrokerServiceSyncHandler.ServeHTTP(w, r)
		case DataBrokerServiceSyncLatestProcedure:
			dataBrokerServiceSyncLatestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDataBrokerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDataBrokerServiceHandler struct{}

func (UnimplementedDataBrokerServiceHandler) AcquireLease(context.Context, *connect.Request[databroker.AcquireLeaseRequest]) (*connect.Response[databroker.AcquireLeaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.AcquireLease is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) Clear(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ClearResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.Clear is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) Get(context.Context, *connect.Request[databroker.GetRequest]) (*connect.Response[databroker.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.Get is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) ListTypes(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ListTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.ListTypes is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) Put(context.Context, *connect.Request[databroker.PutRequest]) (*connect.Response[databroker.PutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.Put is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) Patch(context.Context, *connect.Request[databroker.PatchRequest]) (*connect.Response[databroker.PatchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.Patch is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) Query(context.Context, *connect.Request[databroker.QueryRequest]) (*connect.Response[databroker.QueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.Query is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) ReleaseLease(context.Context, *connect.Request[databroker.ReleaseLeaseRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.ReleaseLease is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) RenewLease(context.Context, *connect.Request[databroker.RenewLeaseRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.RenewLease is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) ServerInfo(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[databroker.ServerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.ServerInfo is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) SetOptions(context.Context, *connect.Request[databroker.SetOptionsRequest]) (*connect.Response[databroker.SetOptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.SetOptions is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) Sync(context.Context, *connect.Request[databroker.SyncRequest], *connect.ServerStream[databroker.SyncResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.Sync is not implemented"))
}

func (UnimplementedDataBrokerServiceHandler) SyncLatest(context.Context, *connect.Request[databroker.SyncLatestRequest], *connect.ServerStream[databroker.SyncLatestResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("databroker.DataBrokerService.SyncLatest is not implemented"))
}

// CheckpointServiceClient is a client for the databroker.CheckpointService service.
type CheckpointServiceClient interface {
	// GetCheckpoint gets the checkpoint.
	GetCheckpoint(context.Context, *connect.Request[databroker.GetCheckpointRequest]) (*connect.Response[databroker.GetCheckpointResponse], error)
	// SetCheckpoint sets the checkpoint.
	SetCheckpoint(context.Context, *connect.Request[databroker.SetCheckpointRequest]) (*connect.Response[databroker.SetCheckpointResponse], error)
}

// NewCheckpointServiceClient constructs a client for the databroker.CheckpointService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCheckpointServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CheckpointServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	checkpointServiceMethods := databroker.File_databroker_proto.Services().ByName("CheckpointService").Methods()
	return &checkpointServiceClient{
		getCheckpoint: connect.NewClient[databroker.GetCheckpointRequest, databroker.GetCheckpointResponse](
			httpClient,
			baseURL+CheckpointServiceGetCheckpointProcedure,
			connect.WithSchema(checkpointServiceMethods.ByName("GetCheckpoint")),
			connect.WithClientOptions(opts...),
		),
		setCheckpoint: connect.NewClient[databroker.SetCheckpointRequest, databroker.SetCheckpointResponse](
			httpClient,
			baseURL+CheckpointServiceSetCheckpointProcedure,
			connect.WithSchema(checkpointServiceMethods.ByName("SetCheckpoint")),
			connect.WithClientOptions(opts...),
		),
	}
}

// checkpointServiceClient implements CheckpointServiceClient.
type checkpointServiceClient struct {
	getCheckpoint *connect.Client[databroker.GetCheckpointRequest, databroker.GetCheckpointResponse]
	setCheckpoint *connect.Client[databroker.SetCheckpointRequest, databroker.SetCheckpointResponse]
}

// GetCheckpoint calls databroker.CheckpointService.GetCheckpoint.
func (c *checkpointServiceClient) GetCheckpoint(ctx context.Context, req *connect.Request[databroker.GetCheckpointRequest]) (*connect.Response[databroker.GetCheckpointResponse], error) {
	return c.getCheckpoint.CallUnary(ctx, req)
}

// SetCheckpoint calls databroker.CheckpointService.SetCheckpoint.
func (c *checkpointServiceClient) SetCheckpoint(ctx context.Context, req *connect.Request[databroker.SetCheckpointRequest]) (*connect.Response[databroker.SetCheckpointResponse], error) {
	return c.setCheckpoint.CallUnary(ctx, req)
}

// CheckpointServiceHandler is an implementation of the databroker.CheckpointService service.
type CheckpointServiceHandler interface {
	// GetCheckpoint gets the checkpoint.
	GetCheckpoint(context.Context, *connect.Request[databroker.GetCheckpointRequest]) (*connect.Response[databroker.GetCheckpointResponse], error)
	// SetCheckpoint sets the checkpoint.
	SetCheckpoint(context.Context, *connect.Request[databroker.SetCheckpointRequest]) (*connect.Response[databroker.SetCheckpointResponse], error)
}

// NewCheckpointServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCheckpointServiceHandler(svc CheckpointServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	checkpointServiceMethods := databroker.File_databroker_proto.Services().ByName("CheckpointService").Methods()
	checkpointServiceGetCheckpointHandler := connect.NewUnaryHandler(
		CheckpointServiceGetCheckpointProcedure,
		svc.GetCheckpoint,
		connect.WithSchema(checkpointServiceMethods.ByName("GetCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	checkpointServiceSetCheckpointHandler := connect.NewUnaryHandler(
		CheckpointServiceSetCheckpointProcedure,
		svc.SetCheckpoint,
		connect.WithSchema(checkpointServiceMethods.ByName("SetCheckpoint")),
		connect.WithHandlerOptions(opts...),
	)
	return "/databroker.CheckpointService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CheckpointServiceGetCheckpointProcedure:
			checkpointServiceGetCheckpointHandler.ServeHTTP(w, r)
		case CheckpointServiceSetCheckpointProcedure:
			checkpointServiceSetCheckpointHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCheckpointServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCheckpointServiceHandler struct{}

func (UnimplementedCheckpointServiceHandler) GetCheckpoint(context.Context, *connect.Request[databroker.GetCheckpointRequest]) (*connect.Response[databroker.GetCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.CheckpointService.GetCheckpoint is not implemented"))
}

func (UnimplementedCheckpointServiceHandler) SetCheckpoint(context.Context, *connect.Request[databroker.SetCheckpointRequest]) (*connect.Response[databroker.SetCheckpointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("databroker.CheckpointService.SetCheckpoint is not implemented"))
}
