/**
 * Client-certificate helpers for the downstream mTLS e2e suite.
 * Adapted from internal/acceptance/browser/helpers/mtls.ts; certificates are
 * generated into .certs/ by setup/certs.ts.
 */

import { Browser, BrowserContext } from "@playwright/test";
import * as path from "path";
import { MTLS_CERTS_DIR } from "../setup/constants.js";

/** Client certificate leaves generated by scripts/gen-certs.sh. */
export type ClientCertType =
  | "valid" // signed by the trusted root CA (SANs: DNS alice.company.com, email alice@company.com)
  | "chain" // signed by the intermediate CA (depth 2)
  | "wrong-ca" // signed by an untrusted CA
  | "san-dns" // SAN DNS:client.san-test.example
  | "san-email" // SAN email:san-user@san-test.example
  | "san-ip" // SAN IP:10.99.1.1
  | "san-uri" // SAN URI:spiffe://san-test.example/client
  | "san-mismatch" // SAN DNS:nomatch.other.example (matches no configured pattern)
  | "revoked" // root-signed leaf listed in crl-root.pem
  | "chain-revoked"; // intermediate-signed leaf listed in crl-intermediate.pem

export function certPaths(certType: ClientCertType): {
  certPath: string;
  keyPath: string;
} {
  if (certType === "chain" || certType === "chain-revoked") {
    // The full chain (leaf + intermediate) must be presented so the server
    // can build the path back to the root CA.
    return {
      certPath: path.join(MTLS_CERTS_DIR, `client-${certType}-full.crt`),
      keyPath: path.join(MTLS_CERTS_DIR, `client-${certType}.key`),
    };
  }
  return {
    certPath: path.join(MTLS_CERTS_DIR, `client-${certType}.crt`),
    keyPath: path.join(MTLS_CERTS_DIR, `client-${certType}.key`),
  };
}

/**
 * Create a browser context that presents the given client certificate
 * (or none, for the "declined certificate" case) to the given origin.
 * The origin must match scheme, host AND port exactly
 * (e.g. https://mtls.localhost.pomerium.io:8443).
 */
export async function newContextWithCert(
  browser: Browser,
  certType: ClientCertType | null,
  originUrl: string
): Promise<BrowserContext> {
  return browser.newContext({
    ignoreHTTPSErrors: true,
    ...(certType
      ? {
          clientCertificates: [
            { origin: new URL(originUrl).origin, ...certPaths(certType) },
          ],
        }
      : {}),
  });
}
