apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: pomerium
          securityContext:
            allowPrivilegeEscalation: false
