apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium
spec:
  template:
    spec:
      containers:
        - name: pomerium
          securityContext:
            readOnlyRootFilesystem: true
