apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pomerium-bootstrap-secret-writer
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
    resourceNames:
      - bootstrap
