// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomerium/pomerium/pkg/grpc/recording (interfaces: RecordClient)
//
// Generated by this command:
//
//	mockgen -package mock_recording -destination ./mock_recording/streams.go . RecordClient
//

// Package mock_recording is a generated GoMock package.
package mock_recording

import (
	context "context"
	reflect "reflect"

	recording "github.com/pomerium/pomerium/pkg/grpc/recording"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockRecordClient is a mock of RecordClient interface.
type MockRecordClient struct {
	ctrl     *gomock.Controller
	recorder *MockRecordClientMockRecorder
	isgomock struct{}
}

// MockRecordClientMockRecorder is the mock recorder for MockRecordClient.
type MockRecordClientMockRecorder struct {
	mock *MockRecordClient
}

// NewMockRecordClient creates a new mock instance.
func NewMockRecordClient(ctrl *gomock.Controller) *MockRecordClient {
	mock := &MockRecordClient{ctrl: ctrl}
	mock.recorder = &MockRecordClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordClient) EXPECT() *MockRecordClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockRecordClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockRecordClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockRecordClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockRecordClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockRecordClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockRecordClient)(nil).Context))
}

// Header mocks base method.
func (m *MockRecordClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockRecordClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockRecordClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockRecordClient) Recv() (*recording.RecordingSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*recording.RecordingSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockRecordClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockRecordClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockRecordClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRecordClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockRecordClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockRecordClient) Send(arg0 *recording.RecordingData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockRecordClientMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRecordClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockRecordClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRecordClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockRecordClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockRecordClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockRecordClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockRecordClient)(nil).Trailer))
}
