// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pomerium/pomerium/pkg/grpc/recording (interfaces: RecordingRecordClient)
//
// Generated by this command:
//
//	mockgen -package mock_recording -destination ./mock_recording/streams.go . RecordingRecordClient
//

// Package mock_recording is a generated GoMock package.
package mock_recording

import (
	context "context"
	reflect "reflect"

	recording "github.com/pomerium/pomerium/pkg/grpc/recording"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockRecordingRecordClient is a mock of RecordingRecordClient interface.
type MockRecordingRecordClient struct {
	ctrl     *gomock.Controller
	recorder *MockRecordingRecordClientMockRecorder
	isgomock struct{}
}

// MockRecordingRecordClientMockRecorder is the mock recorder for MockRecordingRecordClient.
type MockRecordingRecordClientMockRecorder struct {
	mock *MockRecordingRecordClient
}

// NewMockRecordingRecordClient creates a new mock instance.
func NewMockRecordingRecordClient(ctrl *gomock.Controller) *MockRecordingRecordClient {
	mock := &MockRecordingRecordClient{ctrl: ctrl}
	mock.recorder = &MockRecordingRecordClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordingRecordClient) EXPECT() *MockRecordingRecordClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockRecordingRecordClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockRecordingRecordClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockRecordingRecordClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockRecordingRecordClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockRecordingRecordClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockRecordingRecordClient)(nil).Context))
}

// Header mocks base method.
func (m *MockRecordingRecordClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockRecordingRecordClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockRecordingRecordClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockRecordingRecordClient) Recv() (*recording.RecordingData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*recording.RecordingData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockRecordingRecordClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockRecordingRecordClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockRecordingRecordClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRecordingRecordClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockRecordingRecordClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockRecordingRecordClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRecordingRecordClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockRecordingRecordClient)(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockRecordingRecordClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockRecordingRecordClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockRecordingRecordClient)(nil).Trailer))
}
