#!/bin/bash
set -euo pipefail
_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
exec go tool -modfile "$_dir/../internal/tools/go.mod" connectrpc.com/connect/cmd/protoc-gen-connect-go "$@"
