// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: connect.proto

package connect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest is used to subscribe to a stream of messages
// from the Zero Cloud to the Pomerium Core.
//
// The Authorization: Bearer header must contain a valid token,
// that belongs to a cluster identity with appropriate claims set.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SubscribeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Message is an aggregate of all possible messages that can be sent
// from the cloud to the core in managed mode.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Message_ConfigUpdated
	//	*Message_BootstrapConfigUpdated
	//	*Message_TelemetryRequest
	//	*Message_RunHealthChecksRequest
	Message       isMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessage() isMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Message) GetConfigUpdated() *ConfigUpdated {
	if x != nil {
		if x, ok := x.Message.(*Message_ConfigUpdated); ok {
			return x.ConfigUpdated
		}
	}
	return nil
}

func (x *Message) GetBootstrapConfigUpdated() *BootstrapConfigUpdated {
	if x != nil {
		if x, ok := x.Message.(*Message_BootstrapConfigUpdated); ok {
			return x.BootstrapConfigUpdated
		}
	}
	return nil
}

func (x *Message) GetTelemetryRequest() *TelemetryRequest {
	if x != nil {
		if x, ok := x.Message.(*Message_TelemetryRequest); ok {
			return x.TelemetryRequest
		}
	}
	return nil
}

func (x *Message) GetRunHealthChecksRequest() *RunHealthChecksRequest {
	if x != nil {
		if x, ok := x.Message.(*Message_RunHealthChecksRequest); ok {
			return x.RunHealthChecksRequest
		}
	}
	return nil
}

type isMessage_Message interface {
	isMessage_Message()
}

type Message_ConfigUpdated struct {
	ConfigUpdated *ConfigUpdated `protobuf:"bytes,1,opt,name=config_updated,json=configUpdated,proto3,oneof"`
}

type Message_BootstrapConfigUpdated struct {
	BootstrapConfigUpdated *BootstrapConfigUpdated `protobuf:"bytes,2,opt,name=bootstrap_config_updated,json=bootstrapConfigUpdated,proto3,oneof"`
}

type Message_TelemetryRequest struct {
	TelemetryRequest *TelemetryRequest `protobuf:"bytes,3,opt,name=telemetry_request,json=telemetryRequest,proto3,oneof"`
}

type Message_RunHealthChecksRequest struct {
	RunHealthChecksRequest *RunHealthChecksRequest `protobuf:"bytes,5,opt,name=run_health_checks_request,json=runHealthChecksRequest,proto3,oneof"`
}

func (*Message_ConfigUpdated) isMessage_Message() {}

func (*Message_BootstrapConfigUpdated) isMessage_Message() {}

func (*Message_TelemetryRequest) isMessage_Message() {}

func (*Message_RunHealthChecksRequest) isMessage_Message() {}

// ConfigUpdated is sent when the configuration has been updated
// for the connected Pomerium Core deployment
type ConfigUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version of the configuration changeset
	ChangesetVersion int64 `protobuf:"varint,1,opt,name=changeset_version,json=changesetVersion,proto3" json:"changeset_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigUpdated) Reset() {
	*x = ConfigUpdated{}
	mi := &file_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdated) ProtoMessage() {}

func (x *ConfigUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdated.ProtoReflect.Descriptor instead.
func (*ConfigUpdated) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdated) GetChangesetVersion() int64 {
	if x != nil {
		return x.ChangesetVersion
	}
	return 0
}

// BootstrapConfigUpdated is sent when the bootstrap configuration has been
// updated. Bootstrap configuration is received via cluster API directly, and
// does not involve long running operations to construct it, like with a regular
// config.
type BootstrapConfigUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapConfigUpdated) Reset() {
	*x = BootstrapConfigUpdated{}
	mi := &file_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapConfigUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapConfigUpdated) ProtoMessage() {}

func (x *BootstrapConfigUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapConfigUpdated.ProtoReflect.Descriptor instead.
func (*BootstrapConfigUpdated) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{3}
}

// RunHealthChecksRequest is sent to request the Pomerium Core to re-run its health checks
type RunHealthChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunHealthChecksRequest) Reset() {
	*x = RunHealthChecksRequest{}
	mi := &file_connect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHealthChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHealthChecksRequest) ProtoMessage() {}

func (x *RunHealthChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHealthChecksRequest.ProtoReflect.Descriptor instead.
func (*RunHealthChecksRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{4}
}

// TelemetryRequest is sent to request current telemetry data from the Pomerium Core to be sent to the Zero Cloud.
type TelemetryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// include_session_analytics requests current MAU/DAU data
	SessionAnalytics *SessionAnalyticsRequest `protobuf:"bytes,1,opt,name=session_analytics,json=sessionAnalytics,proto3,oneof" json:"session_analytics,omitempty"`
	// envoy_metrics requests current envoy metrics
	EnvoyMetrics *EnvoyMetricsRequest `protobuf:"bytes,2,opt,name=envoy_metrics,json=envoyMetrics,proto3,oneof" json:"envoy_metrics,omitempty"`
	// pomerium_metrics requests current pomerium metrics
	PomeriumMetrics *PomeriumMetricsRequest `protobuf:"bytes,3,opt,name=pomerium_metrics,json=pomeriumMetrics,proto3,oneof" json:"pomerium_metrics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_connect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryRequest) GetSessionAnalytics() *SessionAnalyticsRequest {
	if x != nil {
		return x.SessionAnalytics
	}
	return nil
}

func (x *TelemetryRequest) GetEnvoyMetrics() *EnvoyMetricsRequest {
	if x != nil {
		return x.EnvoyMetrics
	}
	return nil
}

func (x *TelemetryRequest) GetPomeriumMetrics() *PomeriumMetricsRequest {
	if x != nil {
		return x.PomeriumMetrics
	}
	return nil
}

// SessionAnalyticsRequest is used to request current MAU/DAU data
type SessionAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionAnalyticsRequest) Reset() {
	*x = SessionAnalyticsRequest{}
	mi := &file_connect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionAnalyticsRequest) ProtoMessage() {}

func (x *SessionAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*SessionAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{6}
}

// EnvoyMetricsRequest is used to request current envoy metrics
type EnvoyMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// only include metrics that match the provided labels
	Metrics []string `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// only include labels that match the provided labels
	Labels        []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvoyMetricsRequest) Reset() {
	*x = EnvoyMetricsRequest{}
	mi := &file_connect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvoyMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyMetricsRequest) ProtoMessage() {}

func (x *EnvoyMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyMetricsRequest.ProtoReflect.Descriptor instead.
func (*EnvoyMetricsRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{7}
}

func (x *EnvoyMetricsRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EnvoyMetricsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// PomeriumMetricsRequest is used to request current pomerium metrics
type PomeriumMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// only include metrics that match the provided labels
	Metrics       []string `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PomeriumMetricsRequest) Reset() {
	*x = PomeriumMetricsRequest{}
	mi := &file_connect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PomeriumMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomeriumMetricsRequest) ProtoMessage() {}

func (x *PomeriumMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomeriumMetricsRequest.ProtoReflect.Descriptor instead.
func (*PomeriumMetricsRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{8}
}

func (x *PomeriumMetricsRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_connect_proto protoreflect.FileDescriptor

const file_connect_proto_rawDesc = "" +
	"\n" +
	"\rconnect.proto\x12\rpomerium.zero\"H\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf2\x02\n" +
	"\aMessage\x12E\n" +
	"\x0econfig_updated\x18\x01 \x01(\v2\x1c.pomerium.zero.ConfigUpdatedH\x00R\rconfigUpdated\x12a\n" +
	"\x18bootstrap_config_updated\x18\x02 \x01(\v2%.pomerium.zero.BootstrapConfigUpdatedH\x00R\x16bootstrapConfigUpdated\x12N\n" +
	"\x11telemetry_request\x18\x03 \x01(\v2\x1f.pomerium.zero.TelemetryRequestH\x00R\x10telemetryRequest\x12b\n" +
	"\x19run_health_checks_request\x18\x05 \x01(\v2%.pomerium.zero.RunHealthChecksRequestH\x00R\x16runHealthChecksRequestB\t\n" +
	"\amessage\"<\n" +
	"\rConfigUpdated\x12+\n" +
	"\x11changeset_version\x18\x01 \x01(\x03R\x10changesetVersion\"\x18\n" +
	"\x16BootstrapConfigUpdated\"\x18\n" +
	"\x16RunHealthChecksRequest\"\xce\x02\n" +
	"\x10TelemetryRequest\x12X\n" +
	"\x11session_analytics\x18\x01 \x01(\v2&.pomerium.zero.SessionAnalyticsRequestH\x00R\x10sessionAnalytics\x88\x01\x01\x12L\n" +
	"\renvoy_metrics\x18\x02 \x01(\v2\".pomerium.zero.EnvoyMetricsRequestH\x01R\fenvoyMetrics\x88\x01\x01\x12U\n" +
	"\x10pomerium_metrics\x18\x03 \x01(\v2%.pomerium.zero.PomeriumMetricsRequestH\x02R\x0fpomeriumMetrics\x88\x01\x01B\x14\n" +
	"\x12_session_analyticsB\x10\n" +
	"\x0e_envoy_metricsB\x13\n" +
	"\x11_pomerium_metrics\"\x19\n" +
	"\x17SessionAnalyticsRequest\"G\n" +
	"\x13EnvoyMetricsRequest\x12\x18\n" +
	"\ametrics\x18\x01 \x03(\tR\ametrics\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"2\n" +
	"\x16PomeriumMetricsRequest\x12\x18\n" +
	"\ametrics\x18\x01 \x03(\tR\ametrics2Q\n" +
	"\aConnect\x12F\n" +
	"\tSubscribe\x12\x1f.pomerium.zero.SubscribeRequest\x1a\x16.pomerium.zero.Message0\x01B/Z-github.com/pomerium/pomerium/pkg/zero/connectb\x06proto3"

var (
	file_connect_proto_rawDescOnce sync.Once
	file_connect_proto_rawDescData []byte
)

func file_connect_proto_rawDescGZIP() []byte {
	file_connect_proto_rawDescOnce.Do(func() {
		file_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)))
	})
	return file_connect_proto_rawDescData
}

var file_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_connect_proto_goTypes = []any{
	(*SubscribeRequest)(nil),        // 0: pomerium.zero.SubscribeRequest
	(*Message)(nil),                 // 1: pomerium.zero.Message
	(*ConfigUpdated)(nil),           // 2: pomerium.zero.ConfigUpdated
	(*BootstrapConfigUpdated)(nil),  // 3: pomerium.zero.BootstrapConfigUpdated
	(*RunHealthChecksRequest)(nil),  // 4: pomerium.zero.RunHealthChecksRequest
	(*TelemetryRequest)(nil),        // 5: pomerium.zero.TelemetryRequest
	(*SessionAnalyticsRequest)(nil), // 6: pomerium.zero.SessionAnalyticsRequest
	(*EnvoyMetricsRequest)(nil),     // 7: pomerium.zero.EnvoyMetricsRequest
	(*PomeriumMetricsRequest)(nil),  // 8: pomerium.zero.PomeriumMetricsRequest
}
var file_connect_proto_depIdxs = []int32{
	2, // 0: pomerium.zero.Message.config_updated:type_name -> pomerium.zero.ConfigUpdated
	3, // 1: pomerium.zero.Message.bootstrap_config_updated:type_name -> pomerium.zero.BootstrapConfigUpdated
	5, // 2: pomerium.zero.Message.telemetry_request:type_name -> pomerium.zero.TelemetryRequest
	4, // 3: pomerium.zero.Message.run_health_checks_request:type_name -> pomerium.zero.RunHealthChecksRequest
	6, // 4: pomerium.zero.TelemetryRequest.session_analytics:type_name -> pomerium.zero.SessionAnalyticsRequest
	7, // 5: pomerium.zero.TelemetryRequest.envoy_metrics:type_name -> pomerium.zero.EnvoyMetricsRequest
	8, // 6: pomerium.zero.TelemetryRequest.pomerium_metrics:type_name -> pomerium.zero.PomeriumMetricsRequest
	0, // 7: pomerium.zero.Connect.Subscribe:input_type -> pomerium.zero.SubscribeRequest
	1, // 8: pomerium.zero.Connect.Subscribe:output_type -> pomerium.zero.Message
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_connect_proto_init() }
func file_connect_proto_init() {
	if File_connect_proto != nil {
		return
	}
	file_connect_proto_msgTypes[1].OneofWrappers = []any{
		(*Message_ConfigUpdated)(nil),
		(*Message_BootstrapConfigUpdated)(nil),
		(*Message_TelemetryRequest)(nil),
		(*Message_RunHealthChecksRequest)(nil),
	}
	file_connect_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connect_proto_goTypes,
		DependencyIndexes: file_connect_proto_depIdxs,
		MessageInfos:      file_connect_proto_msgTypes,
	}.Build()
	File_connect_proto = out.File
	file_connect_proto_goTypes = nil
	file_connect_proto_depIdxs = nil
}
