# For detailed explanation of each of the configuration settings see
# https://www.pomerium.io/docs/config-reference.htmls

# run pomerium in "all-in-one" mode where all services are run from a single node
omnibusMode: false 

config: # settings that are shared by all services
  sharedSecret: "LL3g/NoKkao7mTec2/wYSOZAki1VbR89q+kqbdFj0c4=" # head -c32 /dev/urandom | base64
  cookieSecret: "tAhd5A5Y8R/H/msFhkNdt8dCym2SatVbh4UrcDk3+Ms=" # head -c32 /dev/urandom | base64
  cert: # base64 -i cert.pem or using a volume
  key:  # base64 -i privkey.pem or using a volume
  policyFile: |-
    - from: httpbin.corp.pomerium.io
      to: http://httpbin
      allowed_domains:
      - pomerium.io
    - from: external-httpbin.corp.pomerium.io
      to: httpbin.org
      allowed_domains:
      - gmail.com
    - from: weirdlyssl.corp.pomerium.io
      to: http://neverssl.com
      allowed_users:
      - bdd@pomerium.io
      allowed_groups:
      - admins
      - developers
    - from: hello.corp.pomerium.io
      to: http://hello:8080
      allowed_groups:
      - admins


authenticate: # values specific to the authenticate service
  name: authenticate # container name
  redirectUrl: https://auth.corp.pomerium.io/oauth2/callback
  proxyRootDomains: pomerium.io
  idp: # see https://www.pomerium.io/docs/identity-providers.html 
    provider: okta
    url: https://example.oktapreview.com/oauth2/default
    clientID: "XXXXXXXX"
    clientSecret: "XXXXXXXX"

authorize: # values specific to the authorize service
  name: authorize # container name

proxy: # values specific to the proxy service
  name: proxy # container name
  authenticateServiceUrl: https://auth.corp.pomerium.io
  authorizeServiceUrl: https://access.corp.pomerium.io

# For any other settings that are optional. for a complete listing see:
# https://www.pomerium.io/docs/config-reference.html
extraEnv: {}
extraArgs: {}
extraVolumes: {}

image:
  repository: "pomerium/pomerium"
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: ClusterIP
  externalPort: 443
  annotations: {}
  # foo.io/bar: "true"
  labels: {}

ingress:
  enabled: false
  # path: /
  # Used to create an Ingress record.
  # hosts:
  #   - "*.corp.example.com"
  #   - "auth.corp.example.com"
  #   - "access.corp.example.com"
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  
  # tls:
  # Secrets must be manually created in the namespace.
  # - secretName: pomerium-tls
  #   hosts:
  #     - chart-example.local
  # secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ## 
  # - name: pomerium-tls
  #   key:
  #   certificate:

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 300Mi

priorityClassName: ""

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
# tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
# nodeSelector: {}

podAnnotations: {}
podLabels: {}
replicaCount: 1
