package main

import (
	"context"
	"errors"
	"iter"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/ettle/strcase"
	"github.com/rs/zerolog/log"
	"google.golang.org/protobuf/reflect/protoreflect"

	configpb "github.com/pomerium/pomerium/pkg/grpc/config"
)

var caser = strcase.NewCaser(true, map[string]bool{
	"JWT": true,
	"MCP": true,
	"PPL": true,
}, nil)

func main() {
	err := run(context.Background())
	if err != nil {
		log.Fatal().Err(err).Send()
	}
}

func run(ctx context.Context) error {
	return generateConfig(ctx)
}

func generateConfig(ctx context.Context) error {
	f := jen.NewFile("config")
	f.PackageComment("// Code generated by internal/generate DO NOT EDIT.")

	mds := []protoreflect.MessageDescriptor{
		new(configpb.BlobStorageSettings).ProtoReflect().Descriptor(),
		new(configpb.Route).ProtoReflect().Descriptor(),
		new(configpb.Settings).ProtoReflect().Descriptor(),
	}
	err := errors.Join(
		generateConfigTypes(ctx, f.Group, mds),
		generateConfigFromProtoFuncs(ctx, f.Group, mds),
		generateConfigToProtoFuncs(ctx, f.Group, mds),
	)
	if err != nil {
		return err
	}
	return f.Save("./config/config.gen.go")
}

func generateConfigFromProtoFuncs(_ context.Context, g *jen.Group, mds []protoreflect.MessageDescriptor) error {
	for _, md := range mds {
		g.Func().
			Id("convert"+getLocalMessageName(md)+"FromProto").
			Params(
				jen.Id("dst").Op("*").Id(getLocalMessageName(md)),
				jen.Id("src").Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
			).
			Params(jen.Id("error")).
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Return().Qual("errors", "Join").CallFunc(func(g *jen.Group) {
					for fd := range iterateMessageFields(md) {
						protoName := string(fd.Name())
						goName := caser.ToPascal(protoName)
						protoGoName := strcase.ToPascal(protoName)
						g.Line().Id("convert"+getFieldTypeName(fd)+"FromProto").Call(
							jen.Op("&").Id("dst").Dot(goName),
							jen.Id("src").Dot(protoGoName),
						)
					}
					g.Line()
				})
			})
		g.Line()
		g.Func().
			Id("convertOptional"+getLocalMessageName(md)+"FromProto").
			Params(
				jen.Id("dst").Op("**").Id(getLocalMessageName(md)),
				jen.Id("src").Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
			).
			Params(jen.Id("error")).
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").New(jen.Id(getLocalMessageName(md)))
				g.Return().Qual("errors", "Join").CallFunc(func(g *jen.Group) {
					for fd := range iterateMessageFields(md) {
						protoName := string(fd.Name())
						goName := caser.ToPascal(protoName)
						protoGoName := strcase.ToPascal(protoName)
						g.Line().Id("convert"+getFieldTypeName(fd)+"FromProto").Call(
							jen.Op("&").Parens(jen.Op("*").Id("dst")).Dot(goName),
							jen.Id("src").Dot(protoGoName),
						)
					}
					g.Line()
				})
			})
		g.Line()
	}
	return nil
}

func generateConfigToProtoFuncs(_ context.Context, g *jen.Group, mds []protoreflect.MessageDescriptor) error {
	for _, md := range mds {
		g.Func().
			Id("convert"+getLocalMessageName(md)+"ToProto").
			Params(
				jen.Id("dst").Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
				jen.Id("src").Op("*").Id(getLocalMessageName(md)),
			).
			Params(jen.Id("error")).
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Return().Qual("errors", "Join").CallFunc(func(g *jen.Group) {
					for fd := range iterateMessageFields(md) {
						protoName := string(fd.Name())
						goName := caser.ToPascal(protoName)
						protoGoName := strcase.ToPascal(protoName)
						g.Line().Id("convert"+getFieldTypeName(fd)+"ToProto").Call(
							jen.Op("&").Id("dst").Dot(protoGoName),
							jen.Id("src").Dot(goName),
						)
					}
					g.Line()
				})
			})
		g.Line()
		g.Func().
			Id("convertOptional"+getLocalMessageName(md)+"ToProto").
			Params(
				jen.Id("dst").Op("**").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
				jen.Id("src").Op("*").Id(getLocalMessageName(md)),
			).
			Params(jen.Id("error")).
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").New(jen.Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)))
				g.Return().Qual("errors", "Join").CallFunc(func(g *jen.Group) {
					for fd := range iterateMessageFields(md) {
						protoName := string(fd.Name())
						goName := caser.ToPascal(protoName)
						protoGoName := strcase.ToPascal(protoName)
						g.Line().Id("convert"+getFieldTypeName(fd)+"ToProto").Call(
							jen.Op("&").Parens(jen.Op("*").Id("dst")).Dot(protoGoName),
							jen.Id("src").Dot(goName),
						)
					}
					g.Line()
				})
			})
		g.Line()
	}
	return nil
}

func generateConfigTypes(_ context.Context, g *jen.Group, mds []protoreflect.MessageDescriptor) error {
	for _, md := range mds {
		g.Type().Id(getLocalMessageName(md)).StructFunc(func(g *jen.Group) {
			for fd := range iterateMessageFields(md) {
				protoName := string(fd.Name())
				goName := caser.ToPascal(protoName)
				g.Id(goName).
					Add(getFieldLocalType(fd)).
					Tag(map[string]string{
						"mapstructure": protoName,
						"yaml":         protoName + ",omitzero",
					})
			}
		})
		g.Line()
	}
	return nil
}

func getFieldLocalType(fd protoreflect.FieldDescriptor) *jen.Statement {
	var s *jen.Statement
	switch fd.Kind() {
	case protoreflect.BoolKind:
		s = jen.Bool()
	case protoreflect.EnumKind:
		panic("enums not implemented")
	case protoreflect.Int32Kind:
		s = jen.Int32()
	case protoreflect.Sint32Kind:
		s = jen.Int32()
	case protoreflect.Uint32Kind:
		s = jen.Uint32()
	case protoreflect.Int64Kind:
		s = jen.Int64()
	case protoreflect.Sint64Kind:
		s = jen.Int64()
	case protoreflect.Uint64Kind:
		s = jen.Uint64()
	case protoreflect.Sfixed32Kind:
		panic("sfixed32 not implemented")
	case protoreflect.Fixed32Kind:
		panic("fixed32 not implemented")
	case protoreflect.FloatKind:
		s = jen.Float32()
	case protoreflect.Sfixed64Kind:
		panic("sfixed64 not implemented")
	case protoreflect.Fixed64Kind:
		panic("fixed64 not implemented")
	case protoreflect.DoubleKind:
		s = jen.Float64()
	case protoreflect.StringKind:
		s = jen.String()
	case protoreflect.BytesKind:
		s = jen.Index().Byte()
	case protoreflect.MessageKind:
		switch fd.Message().FullName() {
		case "google.protobuf.Duration":
			s = jen.Qual("time", "Duration")
		case "google.protobuf.Struct":
			s = jen.Qual("google.golang.org/protobuf/types/known/structpb", "Struct")
		case "google.protobuf.Timestamp":
			s = jen.Qual("time", "Time")
		case "pomerium.config.Route.StringList", "pomerium.config.Settings.StringList":
			s = jen.Index().String()
		default:
			s = jen.Op(getMessageName(fd.Message()))
		}
	case protoreflect.GroupKind:
		panic("groups not implemented")
	default:
		panic("kind not implemented")
	}
	if fd.Cardinality() == protoreflect.Repeated {
		s = jen.Index().Add(s)
	} else if fd.HasOptionalKeyword() {
		s = jen.Op("*").Add(s)
	}
	return s
}

func getFieldTypeName(fd protoreflect.FieldDescriptor) string {
	name := ""
	switch fd.Kind() {
	case protoreflect.BoolKind:
		name = "Boolean"
	case protoreflect.EnumKind:
		panic("enums not implemented")
	case protoreflect.Int32Kind:
		name = "Int32"
	case protoreflect.Sint32Kind:
		name = "Int32"
	case protoreflect.Uint32Kind:
		name = "Uint32"
	case protoreflect.Int64Kind:
		name = "Int64"
	case protoreflect.Sint64Kind:
		name = "Int64"
	case protoreflect.Uint64Kind:
		name = "Uint64"
	case protoreflect.Sfixed32Kind:
		panic("sfixed32 not implemented")
	case protoreflect.Fixed32Kind:
		panic("fixed32 not implemented")
	case protoreflect.FloatKind:
		name = "Float"
	case protoreflect.Sfixed64Kind:
		panic("sfixed64 not implemented")
	case protoreflect.Fixed64Kind:
		panic("fixed64 not implemented")
	case protoreflect.DoubleKind:
		name = "Double"
	case protoreflect.StringKind:
		name = "String"
	case protoreflect.BytesKind:
		name = "Bytes"
	case protoreflect.MessageKind:
		name = getMessageName(fd.Message())
	case protoreflect.GroupKind:
		panic("groups not implemented")
	default:
		panic("kind not implemented")
	}
	if fd.Cardinality() == protoreflect.Repeated {
		name = "Repeated" + name
	} else if fd.HasOptionalKeyword() {
		name = "Optional" + name
	}
	return name
}

func getMessageName(md protoreflect.MessageDescriptor) string {
	msgName := string(md.FullName())
	switch msgName {
	case "google.protobuf.Duration":
		return "Duration"
	case "google.protobuf.Timestamp":
		return "Timestamp"
	case "google.protobuf.Struct":
		return "Struct"
	default:
		msgName = strings.TrimPrefix(msgName, "pomerium.config.")
		msgName = strings.ReplaceAll(msgName, ".", "")
		return msgName
	}
}

func getLocalMessageName(md protoreflect.MessageDescriptor) string {
	name := getMessageName(md)
	switch name {
	case "Route":
		return "RouteOptions"
	case "Settings":
		return "GlobalOptions"
	}
	return name
}

func iterateMessageFields(md protoreflect.MessageDescriptor) iter.Seq[protoreflect.FieldDescriptor] {
	fds := md.Fields()
	var s []protoreflect.FieldDescriptor
	for i := range fds.Len() {
		fd := fds.Get(i)
		if md.FullName() == "pomerium.config.Route" && fd.Number() < 93 {
			continue
		}
		if md.FullName() == "pomerium.config.Settings" && fd.Number() < 170 {
			continue
		}
		s = append(s, fd)
	}
	slices.SortFunc(s, func(a, b protoreflect.FieldDescriptor) int {
		return strings.Compare(string(a.FullName()), string(b.FullName()))
	})
	return slices.Values(s)
}
