package main

import (
	"context"
	"errors"
	"fmt"
	"iter"
	"slices"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/ettle/strcase"
	"github.com/hashicorp/go-set/v3"
	"github.com/rs/zerolog/log"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"

	_ "github.com/pomerium/pomerium/pkg/grpc/config" // config types
)

func main() {
	err := run(context.Background())
	if err != nil {
		log.Fatal().Err(err).Send()
	}
}

func run(ctx context.Context) error {
	return generateConfig(ctx)
}

func generateConfig(ctx context.Context) error {
	f := jen.NewFile("config")
	f.PackageComment("// Code generated by internal/generate DO NOT EDIT.")
	f.ImportAlias("github.com/pomerium/pomerium/pkg/grpc/config", "configpb")
	f.ImportAlias("github.com/pomerium/pomerium/pkg/nullable", ".")

	excludeMessages := set.From([]string{
		"pomerium.config.CertificateInfo",
		"pomerium.config.CircuitBreakerThresholds",
		"pomerium.config.Config",
		"pomerium.config.CreateKeyPairRequest",
		"pomerium.config.CreateKeyPairResponse",
		"pomerium.config.CreatePolicyRequest",
		"pomerium.config.CreatePolicyResponse",
		"pomerium.config.CreateRouteRequest",
		"pomerium.config.CreateRouteResponse",
		"pomerium.config.CreateServiceAccountRequest",
		"pomerium.config.CreateServiceAccountResponse",
		"pomerium.config.DeleteKeyPairRequest",
		"pomerium.config.DeleteKeyPairResponse",
		"pomerium.config.DeletePolicyRequest",
		"pomerium.config.DeletePolicyResponse",
		"pomerium.config.DeleteRouteRequest",
		"pomerium.config.DeleteRouteResponse",
		"pomerium.config.DeleteServiceAccountRequest",
		"pomerium.config.DeleteServiceAccountResponse",
		"pomerium.config.DownstreamMtlsSettings",
		"pomerium.config.EntityInfo",
		"pomerium.config.GetKeyPairRequest",
		"pomerium.config.GetKeyPairResponse",
		"pomerium.config.GetPolicyRequest",
		"pomerium.config.GetPolicyResponse",
		"pomerium.config.GetRouteRequest",
		"pomerium.config.GetRouteResponse",
		"pomerium.config.GetSettingsRequest",
		"pomerium.config.GetSettingsResponse",
		"pomerium.config.GetServerInfoRequest",
		"pomerium.config.GetServerInfoResponse",
		"pomerium.config.GetServiceAccountRequest",
		"pomerium.config.GetServiceAccountResponse",
		"pomerium.config.HealthCheck",
		"pomerium.config.HealthCheck.GrpcHealthCheck",
		"pomerium.config.HealthCheck.HealthStatusSet",
		"pomerium.config.HealthCheck.HttpHealthCheck",
		"pomerium.config.HealthCheck.Int64Range",
		"pomerium.config.HealthCheck.Payload",
		"pomerium.config.HealthCheck.TcpHealthCheck",
		"pomerium.config.KeyPair",
		"pomerium.config.KeyUsage",
		"pomerium.config.ListKeyPairsRequest",
		"pomerium.config.ListKeyPairsResponse",
		"pomerium.config.ListPoliciesRequest",
		"pomerium.config.ListPoliciesResponse",
		"pomerium.config.ListRoutesRequest",
		"pomerium.config.ListRoutesResponse",
		"pomerium.config.ListSettingsRequest",
		"pomerium.config.ListSettingsResponse",
		"pomerium.config.ListServiceAccountsRequest",
		"pomerium.config.ListServiceAccountsResponse",
		"pomerium.config.MCP",
		"pomerium.config.MCPClient",
		"pomerium.config.MCPServer",
		"pomerium.config.Name",
		"pomerium.config.OAuth2Endpoint",
		"pomerium.config.Policy",
		"pomerium.config.PPLPolicy",
		"pomerium.config.Route.StringList",
		"pomerium.config.SANMatcher",
		"pomerium.config.ServiceAccount",
		"pomerium.config.Settings.StringList",
		"pomerium.config.UpdateKeyPairRequest",
		"pomerium.config.UpdateKeyPairResponse",
		"pomerium.config.UpdatePolicyRequest",
		"pomerium.config.UpdatePolicyResponse",
		"pomerium.config.UpdateRouteRequest",
		"pomerium.config.UpdateRouteResponse",
		"pomerium.config.UpdateServiceAccountRequest",
		"pomerium.config.UpdateServiceAccountResponse",
		"pomerium.config.UpdateSettingsRequest",
		"pomerium.config.UpdateSettingsResponse",
		"pomerium.config.UpstreamOAuth2",
		"pomerium.config.UpstreamTunnel",
		"pomerium.config.VersionedConfig",
		"pomerium.config.VersionedConfig.Condition",
	})

	var mds []protoreflect.MessageDescriptor
	protoregistry.GlobalTypes.RangeMessages(func(mt protoreflect.MessageType) bool {
		md := mt.Descriptor()
		name := string(md.FullName())
		if strings.HasPrefix(name, "pomerium.config.") && !excludeMessages.Contains(name) {
			mds = append(mds, md)
		}
		return true
	})
	slices.SortFunc(mds, func(x, y protoreflect.MessageDescriptor) int {
		return strings.Compare(string(x.FullName()), string(y.FullName()))
	})

	err := errors.Join(
		generateConfigTypes(ctx, f.Group, mds),
		generateConfigFromProtoFuncs(ctx, f.Group, mds),
		generateConfigToProtoFuncs(ctx, f.Group, mds),
		generateBasicSetters(ctx, f.Group),
		generateWrappedSetters(ctx, f.Group),
	)
	if err != nil {
		return err
	}
	return f.Save("./config/config.gen.go")
}

func generateConfigTypes(_ context.Context, g *jen.Group, mds []protoreflect.MessageDescriptor) error {
	for _, md := range mds {
		g.Type().Id(getLocalMessageName(md)).StructFunc(func(g *jen.Group) {
			for fd := range iterateMessageFields(md) {
				protoName := string(fd.Name())
				goName := toGoPascalCase(protoName)
				g.Id(goName).
					Add(getFieldLocalType(fd)).
					Tag(map[string]string{
						"mapstructure": protoName,
						"json":         protoName + ",omitzero",
						"yaml":         protoName + ",omitempty",
					})
			}
		})
		g.Line()
	}
	return nil
}

func generateConfigFromProtoFuncs(_ context.Context, g *jen.Group, mds []protoreflect.MessageDescriptor) error {
	for _, md := range mds {
		g.Func().Id("setNullable"+getLocalMessageName(md)+"FromProto").
			Params(
				jen.Id("dst").Op("*").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Id(getLocalMessageName(md))),
				jen.Id("src").Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Id("obj").Op(":=").Id("dst").Dot("Value")
				g.Id("err").Op(":=").Id("set"+getLocalMessageName(md)+"FromProto").Call(jen.Op("&").Id("obj"), jen.Id("src"))
				g.If(jen.Id("err").Op("==").Nil()).Block(jen.Return().Id("err"))
				g.Op("*").Id("dst").Op("=").Qual("github.com/pomerium/pomerium/pkg/nullable", "From").Call(
					jen.Id("obj"),
				)
				g.Return().Nil()
			})
		g.Line()

		g.Func().Id("setNullableSliceOf"+getLocalMessageName(md)+"FromProto").
			Params(
				jen.Id("dst").Op("*").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Index().Id(getLocalMessageName(md))),
				jen.Id("src").Index().Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Id("obj").Op(":=").Id("make").Call(jen.Index().Id(getLocalMessageName(md)), jen.Len(jen.Id("src")))
				g.For(jen.Id("i").Op(":=").Range().Id("src")).BlockFunc(func(g *jen.Group) {
					g.Id("err").Op(":=").Id("set"+getLocalMessageName(md)+"FromProto").Call(
						jen.Op("&").Id("obj").Index(jen.Id("i")),
						jen.Id("src").Index(jen.Id("i")),
					)
					g.If(jen.Id("err").Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
						g.Return().Id("err")
					})
				})
				g.Op("*").Id("dst").Op("=").Qual("github.com/pomerium/pomerium/pkg/nullable", "From").Call(
					jen.Id("obj"),
				)
				g.Return().Nil()
			})
		g.Line()

		g.Func().Id("set"+getLocalMessageName(md)+"FromProto").
			Params(
				jen.Id("dst").Op("*").Id(getLocalMessageName(md)),
				jen.Id("src").Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Return().Qual("errors", "Join").CallFunc(func(g *jen.Group) {
					for fd := range iterateMessageFields(md) {
						protoName := string(fd.Name())
						goName := toGoPascalCase(protoName)
						protoGoName := toProtoPascalCase(protoName)
						setterName := getFieldTypeName(fd)
						if fd.Cardinality() == protoreflect.Repeated {
							setterName = "SliceOf" + setterName
						}
						srcRef := jen.Id("src").Dot(protoGoName)
						if fd.HasOptionalKeyword() {
							// do nothing
						} else if od := fd.ContainingOneof(); od != nil {
							srcRef = jen.Id("getOneOf").Call(
								jen.Id("src").Dot(toProtoPascalCase(string(od.Name()))),
								jen.New(jen.Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)+"_"+protoGoName)),
								jen.Id("src").Dot("Get"+protoGoName).Call(),
							)
						} else if fd.Kind() == protoreflect.MessageKind {
							// do nothing
						} else {
							srcRef = jen.Op("&").Add(srcRef)
						}
						g.Line().Id("setNullable"+setterName+"FromProto").Call(
							jen.Op("&").Id("dst").Dot(goName),
							srcRef,
						)
					}
					g.Line()
				})
			})
		g.Line()
	}
	return nil
}

func generateConfigToProtoFuncs(_ context.Context, g *jen.Group, mds []protoreflect.MessageDescriptor) error {
	for _, md := range mds {
		g.Func().Id("setNullable"+getLocalMessageName(md)+"ToProto").
			Params(
				jen.Id("dst").Op("**").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
				jen.Id("src").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Id(getLocalMessageName(md))),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Op("!").Id("src").Dot("IsSet")).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Return().Id("set"+getLocalMessageName(md)+"ToProto").Call(
					jen.Id("dst"),
					jen.New(jen.Id("src").Dot("Value")),
				)
			})
		g.Line()

		g.Func().Id("setNullableSliceOf"+getLocalMessageName(md)+"ToProto").
			Params(
				jen.Id("dst").Op("*").Index().Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
				jen.Id("src").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Index().Id(getLocalMessageName(md))),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Op("!").Id("src").Dot("IsSet")).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Id("obj").Op(":=").Id("make").Call(
					jen.Index().Op("*").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
					jen.Len(jen.Id("src").Dot("Value")),
				)
				g.For(jen.Id("i").Op(":=").Range().Id("src").Dot("Value")).BlockFunc(func(g *jen.Group) {
					g.Id("err").Op(":=").Id("set"+getLocalMessageName(md)+"ToProto").Call(
						jen.Op("&").Id("obj").Index(jen.Id("i")),
						jen.New(jen.Id("src").Dot("Value").Index(jen.Id("i"))),
					)
					g.If(jen.Id("err").Op("!=").Nil()).BlockFunc(func(g *jen.Group) {
						g.Return().Id("err")
					})
				})
				g.Op("*").Id("dst").Op("=").Id("obj")
				g.Return().Nil()
			})
		g.Line()

		g.Func().
			Id("set"+getLocalMessageName(md)+"ToProto").
			Params(
				jen.Id("dst").Op("**").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)),
				jen.Id("src").Op("*").Id(getLocalMessageName(md)),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.If(jen.Op("*").Id("dst").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Op("*").Id("dst").Op("=").New(jen.Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)))
				})
				g.Id("obj").Op(":=").Op("*").Id("dst")
				g.Return().Qual("errors", "Join").CallFunc(func(g *jen.Group) {
					for fd := range iterateMessageFields(md) {
						protoName := string(fd.Name())
						goName := toGoPascalCase(protoName)
						protoGoName := toProtoPascalCase(protoName)
						setterName := getFieldTypeName(fd)
						if fd.Cardinality() == protoreflect.Repeated {
							setterName = "SliceOf" + setterName
						}
						if fd.HasOptionalKeyword() {
							g.Line().Id("setNullable"+setterName+"ToProto").Call(
								jen.Op("&").Id("obj").Dot(protoGoName),
								jen.Id("src").Dot(goName),
							)
						} else if od := fd.ContainingOneof(); od != nil {
							g.Line().Id("setOneOf").Call(
								jen.Op("&").Id("obj").Dot(toProtoPascalCase(string(od.Name()))),
								jen.Op("&").Qual("github.com/pomerium/pomerium/pkg/grpc/config", getMessageName(md)+"_"+protoGoName).Values(
									jen.Id(protoGoName).Op(":").Id("src").Dot(goName).Dot("Value"),
								),
								jen.Id("src").Dot(goName),
							)
						} else if fd.Kind() == protoreflect.MessageKind {
							g.Line().Id("setNullable"+setterName+"ToProto").Call(
								jen.Op("&").Id("obj").Dot(protoGoName),
								jen.Id("src").Dot(goName),
							)
						} else {
							g.Line().Id("setNullable"+setterName+"ToProto").Call(
								jen.New(jen.Op("&").Id("obj").Dot(protoGoName)),
								jen.Id("src").Dot(goName),
							)
						}
					}
					g.Line()
				})
			})
		g.Line()
	}
	return nil
}

func generateBasicSetters(_ context.Context, g *jen.Group) error {
	type Def struct {
		typeName   string
		methodName string
	}
	baseDefs := []Def{
		{"bool", "Bool"},
		{"byte", "Byte"},
		{"float32", "Float"},
		{"float64", "Double"},
		{"int16", "Int16"},
		{"int32", "Int32"},
		{"int64", "Int64"},
		{"string", "String"},
		{"uint16", "UInt16"},
		{"uint32", "UInt32"},
		{"uint64", "UInt64"},
	}
	allDefs := slices.Clone(baseDefs)
	for _, def := range baseDefs {
		allDefs = append(allDefs, Def{"[]" + def.typeName, "SliceOf" + def.methodName})
	}

	for _, def := range allDefs {
		g.Func().Id("setNullable"+def.methodName+"FromProto").
			Params(
				jen.Id("dst").Op("*").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Id(def.typeName)),
				jen.Id("src").Op("*").Id(def.typeName),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Id("obj").Op(":=").Id("dst").Dot("Value")
				g.Id("err").Op(":=").Id("set"+def.methodName+"FromProto").Call(jen.Op("&").Id("obj"), jen.Id("src"))
				g.If(jen.Id("err").Op("==").Nil()).Block(jen.Return().Id("err"))
				g.Op("*").Id("dst").Op("=").Qual("github.com/pomerium/pomerium/pkg/nullable", "From").Call(
					jen.Id("obj"),
				)
				g.Return().Nil()
			})
		g.Line()

		g.Func().Id("set"+def.methodName+"FromProto").
			Params(
				jen.Id("dst").Op("*").Id(def.typeName),
				jen.Id("src").Op("*").Id(def.typeName),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").Op("*").Id("src")
				g.Return(jen.Nil())
			})
		g.Line()

		g.Func().Id("setNullable"+def.methodName+"ToProto").
			Params(
				jen.Id("dst").Op("**").Id(def.typeName),
				jen.Id("src").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Id(def.typeName)),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Op("!").Id("src").Dot("IsSet")).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").New(jen.Id("src").Dot("Value"))
				g.Return().Nil()
			})
		g.Line()

		g.Func().Id("set"+def.methodName+"ToProto").
			Params(
				jen.Id("dst").Op("**").Id(def.typeName),
				jen.Id("src").Op("*").Id(def.typeName),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").New(jen.Op("*").Id("src"))
				g.Return(jen.Nil())
			})
		g.Line()
	}
	return nil
}

func generateWrappedSetters(_ context.Context, g *jen.Group) error {
	type Def struct {
		typeName   string
		methodName string
	}
	defs := []Def{
		{"bool", "Bool"},
		{"float32", "Float"},
		{"float64", "Double"},
		{"int32", "Int32"},
		{"int64", "Int64"},
		{"string", "String"},
		{"uint32", "UInt32"},
		{"uint64", "UInt64"},
	}
	for _, def := range defs {
		g.Func().Id("setNullable"+def.methodName+"ValueFromProto").
			Params(
				jen.Id("dst").Op("*").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Id(def.typeName)),
				jen.Id("src").Op("*").Qual("google.golang.org/protobuf/types/known/wrapperspb", def.methodName+"Value"),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Id("obj").Op(":=").Id("dst").Dot("Value")
				g.Id("err").Op(":=").Id("set"+def.methodName+"ValueFromProto").Call(jen.Op("&").Id("obj"), jen.Id("src"))
				g.If(jen.Id("err").Op("==").Nil()).Block(jen.Return().Id("err"))
				g.Op("*").Id("dst").Op("=").Qual("github.com/pomerium/pomerium/pkg/nullable", "From").Call(
					jen.Id("obj"),
				)
				g.Return().Nil()
			})
		g.Line()

		g.Func().Id("set"+def.methodName+"ValueFromProto").
			Params(
				jen.Id("dst").Op("*").Id(def.typeName),
				jen.Id("src").Op("*").Qual("google.golang.org/protobuf/types/known/wrapperspb", def.methodName+"Value"),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").Id("src").Dot("Value")
				g.Return(jen.Nil())
			})
		g.Line()

		g.Func().Id("setNullable"+def.methodName+"ValueToProto").
			Params(
				jen.Id("dst").Op("**").Qual("google.golang.org/protobuf/types/known/wrapperspb", def.methodName+"Value"),
				jen.Id("src").Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(jen.Id(def.typeName)),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Op("!").Id("src").Dot("IsSet")).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").Qual("google.golang.org/protobuf/types/known/wrapperspb", def.methodName).Call(jen.Id("src").Dot("Value"))
				g.Return().Nil()
			})
		g.Line()

		g.Func().Id("set"+def.methodName+"ValueToProto").
			Params(
				jen.Id("dst").Op("**").Qual("google.golang.org/protobuf/types/known/wrapperspb", def.methodName+"Value"),
				jen.Id("src").Op("*").Id(def.typeName),
			).
			Error().
			BlockFunc(func(g *jen.Group) {
				g.If(jen.Id("src").Op("==").Nil()).BlockFunc(func(g *jen.Group) {
					g.Return(jen.Nil())
				})
				g.Op("*").Id("dst").Op("=").Qual("google.golang.org/protobuf/types/known/wrapperspb", def.methodName).Call(jen.Op("*").Id("src"))
				g.Return().Nil()
			})
		g.Line()
	}

	return nil
}

func getFieldLocalType(fd protoreflect.FieldDescriptor) *jen.Statement {
	var s *jen.Statement
	switch fd.Kind() {
	case protoreflect.BoolKind:
		s = jen.Bool()
	case protoreflect.EnumKind:
		panic(fmt.Sprintf("enums not implemented: %s", fd.FullName()))
	case protoreflect.Int32Kind:
		s = jen.Int32()
	case protoreflect.Sint32Kind:
		s = jen.Int32()
	case protoreflect.Uint32Kind:
		s = jen.Uint32()
	case protoreflect.Int64Kind:
		s = jen.Int64()
	case protoreflect.Sint64Kind:
		s = jen.Int64()
	case protoreflect.Uint64Kind:
		s = jen.Uint64()
	case protoreflect.Sfixed32Kind:
		panic("sfixed32 not implemented")
	case protoreflect.Fixed32Kind:
		panic("fixed32 not implemented")
	case protoreflect.FloatKind:
		s = jen.Float32()
	case protoreflect.Sfixed64Kind:
		panic("sfixed64 not implemented")
	case protoreflect.Fixed64Kind:
		panic("fixed64 not implemented")
	case protoreflect.DoubleKind:
		s = jen.Float64()
	case protoreflect.StringKind:
		s = jen.String()
	case protoreflect.BytesKind:
		s = jen.Index().Byte()
	case protoreflect.MessageKind:
		switch fd.Message().FullName() {
		case "google.protobuf.BoolValue":
			s = jen.Bool()
		case "google.protobuf.Duration":
			s = jen.Qual("time", "Duration")
		case "google.protobuf.Int16Value":
			s = jen.Int16()
		case "google.protobuf.Int32Value":
			s = jen.Int32()
		case "google.protobuf.Int64Value":
			s = jen.Int64()
		case "google.protobuf.Struct":
			s = jen.Op("*").Qual("google.golang.org/protobuf/types/known/structpb", "Struct")
		case "google.protobuf.Timestamp":
			s = jen.Qual("time", "Time")
		case "google.protobuf.UInt16Value":
			s = jen.Uint16()
		case "google.protobuf.UInt32Value":
			s = jen.Uint32()
		case "google.protobuf.UInt64Value":
			s = jen.Uint64()
		case "pomerium.config.Route.StringList", "pomerium.config.Settings.StringList":
			s = jen.Index().String()
		default:
			s = jen.Id(getMessageName(fd.Message()))
		}
	case protoreflect.GroupKind:
		panic("groups not implemented")
	default:
		panic("kind not implemented")
	}
	if fd.Cardinality() == protoreflect.Repeated {
		s = jen.Index().Add(s)
	}
	s = jen.Qual("github.com/pomerium/pomerium/pkg/nullable", "Value").Index(s)
	return s
}

func getFieldTypeName(fd protoreflect.FieldDescriptor) string {
	name := ""
	switch fd.Kind() {
	case protoreflect.BoolKind:
		name = "Bool"
	case protoreflect.EnumKind:
		panic("enums not implemented")
	case protoreflect.Int32Kind:
		name = "Int32"
	case protoreflect.Sint32Kind:
		name = "Int32"
	case protoreflect.Uint32Kind:
		name = "UInt32"
	case protoreflect.Int64Kind:
		name = "Int64"
	case protoreflect.Sint64Kind:
		name = "Int64"
	case protoreflect.Uint64Kind:
		name = "UInt64"
	case protoreflect.Sfixed32Kind:
		panic("sfixed32 not implemented")
	case protoreflect.Fixed32Kind:
		panic("fixed32 not implemented")
	case protoreflect.FloatKind:
		name = "Float"
	case protoreflect.Sfixed64Kind:
		panic("sfixed64 not implemented")
	case protoreflect.Fixed64Kind:
		panic("fixed64 not implemented")
	case protoreflect.DoubleKind:
		name = "Double"
	case protoreflect.StringKind:
		name = "String"
	case protoreflect.BytesKind:
		name = "SliceOfByte"
	case protoreflect.MessageKind:
		switch fd.Message().FullName() {
		case "pomerium.config.Route.StringList",
			"pomerium.config.Settings.StringList":
			name = "StringList"
		case "google.protobuf.Timestamp":
			name = "Time"
		default:
			name = getMessageName(fd.Message())
		}
	case protoreflect.GroupKind:
		panic("groups not implemented")
	default:
		panic("kind not implemented")
	}
	return name
}

func getMessageName(md protoreflect.MessageDescriptor) string {
	msgName := string(md.FullName())
	msgName = strings.TrimPrefix(msgName, "pomerium.config.")
	msgName = strings.TrimPrefix(msgName, "google.protobuf.")
	msgName = strings.ReplaceAll(msgName, ".", "_")
	return msgName
}

func getLocalMessageName(md protoreflect.MessageDescriptor) string {
	name := getMessageName(md)
	switch name {
	case "Route":
		return "RouteOptions"
	case "Settings":
		return "GlobalOptions"
	}
	return name
}

func iterateMessageFields(md protoreflect.MessageDescriptor) iter.Seq[protoreflect.FieldDescriptor] {
	fds := md.Fields()
	var s []protoreflect.FieldDescriptor
	for i := range fds.Len() {
		fd := fds.Get(i)
		if md.FullName() == "pomerium.config.Route" && fd.Number() < 93 {
			continue
		}
		if md.FullName() == "pomerium.config.Settings" && fd.Number() < 180 {
			continue
		}
		s = append(s, fd)
	}
	slices.SortFunc(s, func(a, b protoreflect.FieldDescriptor) int {
		return strings.Compare(string(a.FullName()), string(b.FullName()))
	})
	return slices.Values(s)
}

func toGoPascalCase(str string) string {
	r := strings.NewReplacer(
		"Uri", "URI",
		"Url", "URL",
		"Id", "ID",
		"Ppl", "PPL",
		"Mcp", "MCP",
		"Ssh", "SSH",
		"CaKey", "CAKey",
		"Jwt", "JWT",
		"Grpc", "GRPC",
		"Dns", "DNS",
		"5xx", "_5xx",
	)
	return r.Replace(strcase.ToPascal(str))
}

func toProtoPascalCase(str string) string {
	r := strings.NewReplacer(
		"5xx", "_5Xx",
	)
	return r.Replace(strcase.ToPascal(str))
}
