# Main configuration flags : https://www.pomerium.io/docs/reference/reference/

pomerium_debug: true
address: :80
cookie_secret: YVFTMIfW8yBJw+a6sYwdW8rHbU+IAAV/SUkCTg9Jtpo=
shared_secret: 80ldlrU2d7w+wVpKNfevk6fmb8otEx6CqOfshj2LwhQ=

idp_provider: "google"
idp_client_id: REPLACEME
idp_client_secret: REPLACEME

insecure_server: true
forward_auth_url: http://pomerium
authenticate_service_url: https://authenticate.localhost.pomerium.io

policy:
  - from: https://httpbin.localhost.pomerium.io
    to: https://httpbin
    allowed_domains:
      - pomerium.io
      - gmail.com
