version: "3"
services:
  nginx:
    image: openresty/openresty
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../examples/nginx/verify.conf:/etc/nginx/conf.d/verify.conf
      - ../../examples/nginx/pomerium.conf:/etc/nginx/conf.d/pomerium.conf
      - ../../examples/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ../../examples/nginx/_wildcard.localhost.pomerium.io.pem:/etc/nginx/nginx.pem
      - ../../examples/nginx/_wildcard.localhost.pomerium.io-key.pem:/etc/nginx/nginx-key.pem

  verify:
    image: pomerium/verify
    expose:
      - 80

  pomerium:
    build: ../.
    volumes:
      - ../../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - INSECURE_SERVER=TRUE
      - ADDRESS=:80
      - FORWARD_AUTH_URL=https://fwdauth.localhost.pomerium.io
      - JWT_CLAIMS_HEADERS="email,groups,user"
    expose:
      - 80
