name: Docker Main
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    outputs:
      sha-tag: ${{ steps.metadata.outputs.sha-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .tool-versions

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: .tool-versions

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e

      - name: Login to DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Image Metadata
        id: metadata
        run: |
          IMAGE=pomerium/pomerium
          SHA_TAG=git-${GITHUB_SHA::8}
          TAGS="${IMAGE}:main ${IMAGE}:master ${IMAGE}:${SHA_TAG}"
          TS=$(date +%Y%m%d%H%M%S)
          {
            echo "tags=${TAGS}"
            echo "timestamp=${TS}"
            echo "name=pomerium"
            echo "sha-tag=${SHA_TAG}"
          } >> "$GITHUB_OUTPUT"

      - name: Build Binary
        run: |
          set -euo pipefail
          make build-ui

          mkdir -p dist/docker/amd64 dist/docker/arm64

          GOOS=linux GOARCH=amd64 make build-go
          cp bin/pomerium dist/docker/amd64/pomerium

          GOOS=linux GOARCH=arm64 make build-go
          cp bin/pomerium dist/docker/arm64/pomerium

      - name: Docker Publish - Main AMD64
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./dist/docker/amd64
          file: ./.github/Dockerfile-release
          push: true
          platforms: linux/amd64
          provenance: false
          tags: pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-amd64
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Main ARM64
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./dist/docker/arm64
          file: ./.github/Dockerfile-release
          push: true
          platforms: linux/arm64
          provenance: false
          tags: pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-arm64v8
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Main Manifest
        run: |
          for tag in ${{ steps.metadata.outputs.tags }}
          do
            docker manifest create -a $tag \
              pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-amd64 \
              pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-arm64v8
            docker manifest push $tag
          done

      - name: Docker Publish - Debug Main AMD64
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./dist/docker/amd64
          file: ./.github/Dockerfile-release-debug
          push: true
          platforms: linux/amd64
          provenance: false
          tags: pomerium/pomerium:debug-amd64-main
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Debug Main ARM64
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./dist/docker/arm64
          file: ./.github/Dockerfile-release-debug
          push: true
          platforms: linux/arm64
          provenance: false
          tags: pomerium/pomerium:debug-arm64v8-main
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Debug Main Manifest
        run: |
          docker manifest create -a pomerium/pomerium:debug-main \
            pomerium/pomerium:debug-amd64-main \
            pomerium/pomerium:debug-arm64v8-main
          docker manifest push pomerium/pomerium:debug-main

  deploy:
    runs-on: ubuntu-22.04
    needs: publish
    steps:
      - name: Checkout Gitops Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: pomerium/gitops-argocd
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Bump psql environment
        uses: mikefarah/yq@c14f446382944492701b16c1ddb48bb9dbe683e3
        with:
          cmd:
            yq eval '.pomerium.image.tag = "${{ needs.publish.outputs.sha-tag }}"' -i
            projects/pomerium-master-postgres/pomerium/values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d
        with:
          commit_message: |
            Bump test environment pomerium/pomerium
            Image tag: ${{ needs.publish.outputs.sha-tag }}
            Source Repo: ${{ github.repository }}@${{ github.sha }}
