name: Docker Main
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    outputs:
      sha-tag: ${{ steps.metadata.outputs.sha-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .tool-versions

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: .tool-versions

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Image Metadata
        id: metadata
        run: |
          IMAGE=pomerium/pomerium
          SHA_TAG=git-${GITHUB_SHA::8}
          TAGS="${IMAGE}:main ${IMAGE}:master ${IMAGE}:${SHA_TAG}"
          TS=$(date +%Y%m%d%H%M%S)
          {
            echo "tags=${TAGS}"
            echo "timestamp=${TS}"
            echo "name=pomerium"
            echo "sha-tag=${SHA_TAG}"
          } >> "$GITHUB_OUTPUT"

      - name: Build Binary
        run: |
          set -euo pipefail
          make build-ui

          mkdir -p dist/docker/amd64 dist/docker/arm64

          GOOS=linux GOARCH=amd64 make build-go
          cp bin/pomerium dist/docker/amd64/pomerium

          GOOS=linux GOARCH=arm64 make build-go
          cp bin/pomerium dist/docker/arm64/pomerium

      - name: Docker Publish - Main AMD64
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: ./dist/docker/amd64
          file: ./.github/Dockerfile-release
          push: true
          platforms: linux/amd64
          provenance: false
          tags: pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-amd64
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Main ARM64
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: ./dist/docker/arm64
          file: ./.github/Dockerfile-release
          push: true
          platforms: linux/arm64
          provenance: false
          tags: pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-arm64v8
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Main Manifest
        run: |
          for tag in ${{ steps.metadata.outputs.tags }}
          do
            docker manifest create -a $tag \
              pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-amd64 \
              pomerium/pomerium:${{ steps.metadata.outputs.sha-tag }}-arm64v8
            docker manifest push $tag
          done

      - name: Docker Publish - Debug Main AMD64
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: ./dist/docker/amd64
          file: ./.github/Dockerfile-release-debug
          push: true
          platforms: linux/amd64
          provenance: false
          tags: pomerium/pomerium:debug-amd64-main
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Debug Main ARM64
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: ./dist/docker/arm64
          file: ./.github/Dockerfile-release-debug
          push: true
          platforms: linux/arm64
          provenance: false
          tags: pomerium/pomerium:debug-arm64v8-main
          labels: |
            org.opencontainers.image.created=${{ steps.metadata.outputs.timestamp }}
            org.opencontainers.image.name=${{ steps.metadata.outputs.name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Docker Publish - Debug Main Manifest
        run: |
          docker manifest create -a pomerium/pomerium:debug-main \
            pomerium/pomerium:debug-amd64-main \
            pomerium/pomerium:debug-arm64v8-main
          docker manifest push pomerium/pomerium:debug-main

  deploy:
    runs-on: ubuntu-22.04
    needs: publish
    steps:
      - name: Checkout Gitops Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: pomerium/gitops-argocd
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Bump psql environment
        uses: mikefarah/yq@751d8ad57b84f1794661bc70c0afb92a22ad7b3c
        with:
          cmd:
            yq eval '.pomerium.image.tag = "${{ needs.publish.outputs.sha-tag }}"' -i
            projects/pomerium-master-postgres/pomerium/values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          commit_message: |
            Bump test environment pomerium/pomerium
            Image tag: ${{ needs.publish.outputs.sha-tag }}
            Source Repo: ${{ github.repository }}@${{ github.sha }}
