name: govulncheck
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**/go.mod"
      - "**/go.sum"
      - go.work
      - go.work.sum
      - Makefile
      - .github/workflows/govulncheck.yaml
  schedule:
    - cron: "17 6 * * 1"
  workflow_dispatch: {}

jobs:
  govulncheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: .tool-versions
          cache: false

      - run: make deps-build

      - run: make govulncheck
