name: Lint
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: .tool-versions
          cache: false

      - run: make deps-build

      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
        with:
          version-file: .tool-versions
          args: --timeout=10m
