name: Notify Dependencies

permissions: {}

on:
  push:
    branches:
      - main
      - 0-[0-9]+-*

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - cli
          - hosted-authenticate
          - ingress-controller
          - pomerium-console
          - pomerium-zero
          - terraform-provider-pomerium
          - ui
    steps:
      - name: Notify
        uses: benc-uk/workflow-dispatch@d004979be141727c7a17c28f603e2facc40d0855
        with:
          ref: main
          repo: pomerium/${{ matrix.repo }}
          sync-status: true
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          wait-for-completion: true
          workflow: update-dependencies.yaml
