name: Update Dependencies

on:
  pull_request:
  schedule:
    - cron: "40 1 * * *"
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update Main Dependencies
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26
        with:
          workflow: update-branch-dependencies.yaml
          inputs: '{"branch":"main"}'
