name: Update Dependencies

on:
  schedule:
    - cron: "40 1 * * *"
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        uses: rez0n/actions-github-release@05fabbd6b2b3ce3383299555ea518faea69b736d
        id: latest_release
        with:
          repository: ${{ github.repository }}
          type: "stable"

      - name: Get Latest Release Branch
        id: latest_release_branch
        run: |
          latest_release_branch="$(echo ${{ steps.latest_release.outputs.release }} | sed -E 's/^v?([0-9]+)[.]([0-9]+)[.].*$/\1-\2-0/')"
          echo "value=$latest_release_branch" >> "$GITHUB_OUTPUT"

      - name: Trigger Update Latest Release Dependencies
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26
        with:
          workflow: update-branch-dependencies.yaml
          inputs: '{"branch":"${{ steps.latest_release_branch.outputs.value }}"}'

      - name: Trigger Update Main Dependencies
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26
        with:
          workflow: update-branch-dependencies.yaml
          inputs: '{"branch":"main"}'
