name: Update Branch Dependencies
run-name: Update ${{ inputs.branch }} Dependencies

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to run the script on
        default: main
        required: false
        type: string

jobs:
  update-branch-depenencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Setup ASDF
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47

      - name: Update Tools
        run: ./scripts/update-dependencies tools

      - name: Update Docker Dependencies
        run: ./scripts/update-dependencies docker

      - name: Update Pomerium Dependencies
        if: ${{ inputs.branch == 'main' }}
        run: ./scripts/update-dependencies pomerium

      - name: Proto
        run: make proto

      - name: GoReleaser checks
        env:
          GOTOOLCHAIN: local
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          make goreleaser-check snapshot

