apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pomerium-zero
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: pomerium-zero
resources:
  - namespace.yaml
  - ./rbac
  - ./deployment
  - ./service
